//generated by exodus "compile btreeextract"
//#ifndef EXODUSDLFUNC_BTREEEXTRACT_H
#define EXODUSDLFUNC_BTREEEXTRACT_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_btreeextract;
class efb_btreeextract : private ExodusFunctorBase
{
public:

efb_btreeextract(MvEnvironment& mv) : ExodusFunctorBase("btreeextract", "exodusprogrambasecreatedelete_", mv) {}

efb_btreeextract& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in cmd, in filename, in dictfile, out hits)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_btreeextract.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_btreeextract.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (cmd,filename,dictfile,hits);

}

};
efb_btreeextract btreeextract{mv};
//#endif
