//generated by exodus "compile ../sys/collectixvals"
//#ifndef EXODUSDLFUNC_COLLECTIXVALS_H
#define EXODUSDLFUNC_COLLECTIXVALS_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_collectixvals;
class efb_collectixvals : private ExodusFunctorBase
{
public:

efb_collectixvals(MvEnvironment& mv) : ExodusFunctorBase("collectixvals", "exodusprogrambasecreatedelete_", mv) {}

efb_collectixvals& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in filename, in dictid, in prefix="", in orderby="")
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_collectixvals.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_collectixvals.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (filename,dictid,prefix,orderby);

}

};
efb_collectixvals collectixvals{mv};
//#endif
