//generated by exodus "compile convpdf"
//#ifndef EXODUSDLFUNC_CONVPDF_H
#define EXODUSDLFUNC_CONVPDF_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_convpdf;
class efb_convpdf : private ExodusFunctorBase
{
public:

efb_convpdf(MvEnvironment& mv) : ExodusFunctorBase("convpdf", "exodusprogrambasecreatedelete_", mv) {}

efb_convpdf& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in printopts0, out errors)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_convpdf.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_convpdf.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (printopts0,errors);

}

};
efb_convpdf convpdf{mv};
//#endif
