//generated by exodus "compile ../sys/listen2"
//#ifndef EXODUSDLFUNC_LISTEN2_H
#define EXODUSDLFUNC_LISTEN2_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_listen2;
class efb_listen2 : private ExodusFunctorBase
{
public:

efb_listen2(MvEnvironment& mv) : ExodusFunctorBase("listen2", "exodusprogrambasecreatedelete_", mv) {}

efb_listen2& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in request1, in request2, in request3, in request4, io request5, in request6="")
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,in,io,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_listen2.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_listen2.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (request1,request2,request3,request4,request5,request6);

}

};
efb_listen2 listen2{mv};
//#endif
