//generated by exodus "compile loginnet"
//#ifndef EXODUSDLFUNC_LOGINNET_H
#define EXODUSDLFUNC_LOGINNET_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_loginnet;
class efb_loginnet : private ExodusFunctorBase
{
public:

efb_loginnet(MvEnvironment& mv) : ExodusFunctorBase("loginnet", "exodusprogrambasecreatedelete_", mv) {}

efb_loginnet& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in dataset, in username, io cookie, io msg, io authcompcodes)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,io,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_loginnet.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_loginnet.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (dataset,username,cookie,msg,authcompcodes);

}

};
efb_loginnet loginnet{mv};
//#endif
