//generated by exodus "compile ../sys/rtp57"
//#ifndef EXODUSDLFUNC_RTP57_H
#define EXODUSDLFUNC_RTP57_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_rtp57;
class efb_rtp57 : private ExodusFunctorBase
{
public:

efb_rtp57(MvEnvironment& mv) : ExodusFunctorBase("rtp57", "exodusprogrambasecreatedelete_", mv) {}

efb_rtp57& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in code, in fs, io handle, in keyorfilename, in fmc, io record, io status)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,io,in,in,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_rtp57.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_rtp57.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (code,fs,handle,keyorfilename,fmc,record,status);

}

};
efb_rtp57 rtp57{mv};
//#endif
