//generated by exodus "compile shadowmfs"
//#ifndef EXODUSDLFUNC_SHADOWMFS_H
#define EXODUSDLFUNC_SHADOWMFS_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_shadowmfs;

//a member function with the right arguments, returning a var or void
var shadowmfs(in mode, in options)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_shadowmfs.pmemberfunction_==NULL)
  efb_shadowmfs.init("shadowmfs","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_shadowmfs.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_shadowmfs.pmemberfunction_)))
  (mode,options);

}
//#endif
