//generated by exodus "compile ../sys/shell2"
//#ifndef EXODUSDLFUNC_SHELL2_H
#define EXODUSDLFUNC_SHELL2_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_shell2;

//a member function with the right arguments, returning a var or void
var shell2(in cmd,out errors)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_shell2.pmemberfunction_==NULL)
  efb_shell2.init("shell2","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_shell2.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_shell2.pmemberfunction_)))
  (cmd,errors);

}
//#endif
