//generated by exodus "compile ../sys/sortarray"
//#ifndef EXODUSDLFUNC_SORTARRAY_H
#define EXODUSDLFUNC_SORTARRAY_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_sortarray;
class efb_sortarray : private ExodusFunctorBase
{
public:

efb_sortarray(MvEnvironment& mv) : ExodusFunctorBase("sortarray", "exodusprogrambasecreatedelete_", mv) {}

efb_sortarray& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (io array, in fns, in order="A", in justification="L")
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(io,in,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_sortarray.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_sortarray.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (array,fns,order,justification);

}

};
efb_sortarray sortarray{mv};
//#endif
