//generated by exodus "compile ../sys/taghtml"
//#ifndef EXODUSDLFUNC_TAGHTML_H
#define EXODUSDLFUNC_TAGHTML_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_taghtml;
class efb_taghtml : private ExodusFunctorBase
{
public:

efb_taghtml(MvEnvironment& mv) : ExodusFunctorBase("taghtml", "exodusprogrambasecreatedelete_", mv) {}

efb_taghtml& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in type, in in0, in mode, out output)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_taghtml.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_taghtml.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (type,in0,mode,output);

}

var operator() (in type, in in0, in mode, in output=var()) {
 var output_out;
 if (output.assigned()) output_out=output;
 return operator()(type,in0,mode,output_out);
}

};
efb_taghtml taghtml{mv};
//#endif
