//generated by exodus "compile ../sys/trim2"
//#ifndef EXODUSDLFUNC_TRIM2_H
#define EXODUSDLFUNC_TRIM2_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_trim2;
class efb_trim2 : private ExodusFunctorBase
{
public:

efb_trim2(MvEnvironment& mv) : ExodusFunctorBase("trim2", "exodusprogrambasecreatedelete_", mv) {}

efb_trim2& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in string1, in char1, in fb=var())
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_trim2.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_trim2.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (string1,char1,fb);

}

};
efb_trim2 trim2{mv};
//#endif
