//generated by exodus "compile ../sys/xrefsubs"
//#ifndef EXODUSDLFUNC_XREFSUBS_H
#define EXODUSDLFUNC_XREFSUBS_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_xrefsubs;

//a member function with the right arguments, returning a var or void
var xrefsubs(in mode, in subfn, in masterfilename, io masterfile, in masterfn, io locklist)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_xrefsubs.pmemberfunction_==NULL)
  efb_xrefsubs.init("xrefsubs","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,io,in,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_xrefsubs.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_xrefsubs.pmemberfunction_)))
  (mode,subfn,masterfilename,masterfile,masterfn,locklist);

}
//#endif
