//generated by exodus "compile ../sys/xselect"
//#ifndef EXODUSDLFUNC_XSELECT_H
#define EXODUSDLFUNC_XSELECT_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_xselect;

//a member function with the right arguments, returning a var or void
var xselect(in cmd)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_xselect.pmemberfunction_==NULL)
  efb_xselect.init("xselect","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_xselect.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_xselect.pmemberfunction_)))
  (cmd);

}
//#endif
