#!/bin/bash

rm -I -f */*~ */*.2 */eevalt.cpp
rm -I -f *~ *.2 eevalt.cpp 2>/dev/null

rm -I -f */NLOG */LOG */NEOSYS.CFG
rm -I -f NLOG LOG NEOSYS.CFG

rm -I -rf */DATAVOL\\*
rm -I -rf DATAVOL\\*

rm -I -f arev/*

