#!/bin/bash
#DEBHELPER#
set -e
if [ -f /etc/php5/conf.d/exodus.ini ]; then
 rm /etc/php5/conf.d/exodus.ini
 test -f /etc/init.d/apache2 && ( /etc/init.d/apache2 restart || echo "there was some issue restarting apache" )
fi
