#ifndef ExodusFunctorF0_H
#define ExodusFunctorF0_H

//generated by genfunctors.cpp

#include <exodus/mvfunctor.h>

template<>
class ExodusFunctorF0 : private ExodusFunctorBase
{
public:
 ExodusFunctorF0(const std::string libname,const std::string funcname)
	: ExodusFunctorBase(libname,funcname){}

 var operator() ()
 {
	checkload();
	typedef var (*ExodusDynamic)();
	return  ((ExodusDynamic) _pfunction)();
 }

};
#endif
