#!/bin/bash
set -eux

: ================================================================
: Compile EXODUS service programs and install script and dat files
: ================================================================
:
: Please ignore a few warnings only about 'cast between incompatible pointer to member types'
:
	COMPILER_OPTIONS=${1:-}

:
: "dat" means no compilations and only copy dat files
: ===================================================
:
	if [ "$COMPILER_OPTIONS" = "dat" ];then
		COMPILER_OPTIONS=X
	fi

#:
#: Install the latest version of the neomail script into test
#: ==========================================================
#:
#: neomail is only used by backup_db and will be removed once that is replaced by sendmail direct
#:
#	rsync -av --whole-file ~/exodus/service/neomail ~/bin/

:
: Generate all headers first
: ==========================
:
	compile alt exo sys {HS$COMPILER_OPTIONS}

:
: Compile EXODUS service
: ======================
:
: O - optimize level 1
: S - silent. Only stars
:
	compile alt exo sys {OS${COMPILER_OPTIONS}}

:
: Install dat files
: =================
:
	# Do not delete because dict.voc is merged with applications
	# Empty files will be deleted in the end
	#rsync -avz --delete ./dat/* ~/dat/
	rsync -avz ./dat/* ~/dat/

:
: Flag sync_dat to review all
: ===========================
:
	touch ~/dat

:
: Finished compiling EXODUS service in $(($SECONDS/60)) minutes and $(($SECONDS%60)) seconds.
: =================================================================
