#!/bin/bash
set -eux

: ======================
: Compile EXODUS service
: ======================
:
:   Please ignore compile error on sys/serve_exo.cpp and various warnings
:
:
: Generate all headers first
: ==========================
:
	compile alt exo sys {HS}

:
: Compile EXODUS service
: ======================
:
	compile alt exo sys {S}

:
: Finished compiling EXODUS service in $(($SECONDS/60)) minutes and $(($SECONDS%60)) seconds.
: =================================================================
