#!/bin/bash

if ! test -f ../getarev ; then echo must be run in service/src/??? ; exit; fi

set -x
set -e

:
: function change neosys to exodus in all text - except neosys.com
:
function convneosys2exodus {
	find ../$MODULE -type f -exec sed -i 's#neosys#exodus#g' {} \;
	find ../$MODULE -type f -exec sed -i 's#exodus\.com#neosys.com#g' {} \;
	find ../$MODULE -type f -exec sed -i 's#NEOSYS#EXODUS#g' {} \;
	find ../$MODULE -type f -exec sed -i 's#Copyright EXODUS#Copyright NEOSYS#g' {} \;
}
:
: dont get headers for sys from arev
:
MODULE=sys
mkdir -p  ../$MODULE
cp ~/arev/$MODULE/*.cpp ../$MODULE/
convneosys2exodus sys

for MODULE in gen fin agy med job tim
do
	mkdir -p  ../$MODULE
	cp ~/arev/$MODULE/*.cpp ~/arev/$MODULE/*.h ../$MODULE/
	convneosys2exodus sys $MODULE
#	compile ../$MODULE/*.cpp {S}
done

set +x
