#!/bin/bash
set -euxo pipefail

: =====================
: Make exodus sql files
: =====================
:

	DB_FILENAMES='dict.changelog dict.definitions dict.locks dict.processes dict.requestlog dict.statistics dict.users dict.voc'

	for DB_FILENAME in $DB_FILENAMES; do

		:
		: Output filename to be like sql/dict.changelog.sql
		:
			OS_FILENAME=sql/$DB_FILENAME.sql

		:
		: pg_dump
		:
			sudo -u postgres pg_dump exodus --table $DB_FILENAME > $OS_FILENAME

	done
