#!/bin/bash
set -euxo pipefail

: ==========================================
: Make exodus dat files from exodus database
: ==========================================
:
: Obsolete now that dictionaries are developed in dat files
:
	exit

	copyfile exodus:dict.changelog,dict.definitions,dict.locks,dict.processes,dict.requestlog,dict.statistics,dict.users,dict.voc ./dat
