//generated by exodus "compile addcent4"
//#ifndef EXODUSDLFUNC_ADDCENT4_H
#define EXODUSDLFUNC_ADDCENT4_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_addcent4;
class efb_addcent4 : public ExodusFunctorBase
{
public:

efb_addcent4(MvEnvironment& mv) : ExodusFunctorBase("addcent4", "exodusprogrambasecreatedelete_", mv) {}

efb_addcent4& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in type, in in0, in mode, out outx)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_addcent4.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_addcent4.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (type,in0,mode,outx);

}

var operator() () {
 var type_in;
 var in0_in;
 var mode_in;
 var outx_out;
 return operator()(type_in, in0_in, mode_in, outx_out);
}

var operator() (in type) {
 var in0_in;
 var mode_in;
 var outx_out;
 return operator()(type, in0_in, mode_in, outx_out);
}

var operator() (in type, in in0) {
 var mode_in;
 var outx_out;
 return operator()(type, in0, mode_in, outx_out);
}

var operator() (in type, in in0, in mode) {
 var outx_out;
 return operator()(type, in0, mode, outx_out);
}

};
efb_addcent4 addcent4{mv};
//#endif
