//generated by exodus "compile ../sys/convertercsv"
//#ifndef EXODUSDLFUNC_CONVERTERCSV_H
#define EXODUSDLFUNC_CONVERTERCSV_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_convertercsv;
class efb_convertercsv : public ExodusFunctorBase
{
public:

efb_convertercsv(MvEnvironment& mv) : ExodusFunctorBase("convertercsv", "exodusprogrambasecreatedelete_", mv) {}

efb_convertercsv& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode, io line, in params, in filename)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,io,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_convertercsv.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_convertercsv.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,line,params,filename);

}

var operator() () {
 var mode_in;
 var line_io;
 var params_in;
 var filename_in;
 return operator()(mode_in, line_io, params_in, filename_in);
}

var operator() (in mode) {
 var line_io;
 var params_in;
 var filename_in;
 return operator()(mode, line_io, params_in, filename_in);
}

var operator() (in mode, io line) {
 var params_in;
 var filename_in;
 return operator()(mode, line, params_in, filename_in);
}

var operator() (in mode, io line, in params) {
 var filename_in;
 return operator()(mode, line, params, filename_in);
}

};
efb_convertercsv convertercsv{mv};
//#endif
