//generated by exodus "compile convcsv"
//#ifndef EXODUSDLFUNC_CONVCSV_H
#define EXODUSDLFUNC_CONVCSV_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_convcsv;
class efb_convcsv : public ExodusFunctorBase
{
public:

efb_convcsv(MvEnvironment& mv) : ExodusFunctorBase("convcsv", "exodusprogrambasecreatedelete_", mv) {}

efb_convcsv& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in sentence0, in select0="", in filters0="")
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_convcsv.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_convcsv.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (sentence0,select0,filters0);

}

var operator() () {
 var sentence0_in;
 var select0_in = "";
 var filters0_in = "";
 return operator()(sentence0_in, select0_in, filters0_in);
}

};
efb_convcsv convcsv{mv};
//#endif
