//generated by exodus "compile crosstab"
//#ifndef EXODUSDLFUNC_CROSSTAB_H
#define EXODUSDLFUNC_CROSSTAB_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_crosstab;
class efb_crosstab : public ExodusFunctorBase
{
public:

efb_crosstab(MvEnvironment& mv) : ExodusFunctorBase("crosstab", "exodusprogrambasecreatedelete_", mv) {}

efb_crosstab& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin, io filterout, io allrowvals, io allcolvals, io prefixes, io prefixmvfn)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,in,io,io,io,io,io,io,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_crosstab.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_crosstab.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (filename,rowfields0,colfield,datafield,table,filterdictid,filterin,filterout,allrowvals,allcolvals,prefixes,prefixmvfn);

}

var operator() () {
 var filename_in;
 var rowfields0_in;
 var colfield_in;
 var datafield_in;
 var table_io;
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename_in, rowfields0_in, colfield_in, datafield_in, table_io, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename) {
 var rowfields0_in;
 var colfield_in;
 var datafield_in;
 var table_io;
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0_in, colfield_in, datafield_in, table_io, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0) {
 var colfield_in;
 var datafield_in;
 var table_io;
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield_in, datafield_in, table_io, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield) {
 var datafield_in;
 var table_io;
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield_in, table_io, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield) {
 var table_io;
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table_io, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table) {
 var filterdictid_io;
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid_io, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid) {
 var filterin_io;
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin_io, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin) {
 var filterout_io;
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin, filterout_io, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin, io filterout) {
 var allrowvals_io;
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin, filterout, allrowvals_io, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin, io filterout, io allrowvals) {
 var allcolvals_io;
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin, filterout, allrowvals, allcolvals_io, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin, io filterout, io allrowvals, io allcolvals) {
 var prefixes_io;
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin, filterout, allrowvals, allcolvals, prefixes_io, prefixmvfn_io);
}

var operator() (in filename, in rowfields0, in colfield, in datafield, io table, io filterdictid, io filterin, io filterout, io allrowvals, io allcolvals, io prefixes) {
 var prefixmvfn_io;
 return operator()(filename, rowfields0, colfield, datafield, table, filterdictid, filterin, filterout, allrowvals, allcolvals, prefixes, prefixmvfn_io);
}

};
efb_crosstab crosstab{mv};
//#endif
