//generated by exodus "compile ../sys/date"
//#ifndef EXODUSDLFUNC_DATE_H
#define EXODUSDLFUNC_DATE_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_date;
class efb_date : public ExodusFunctorBase
{
public:

efb_date(MvEnvironment& mv) : ExodusFunctorBase("date", "exodusprogrambasecreatedelete_", mv) {}

efb_date& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in type, in in0, in mode0, out output, in glang)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_date.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_date.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (type,in0,mode0,output,glang);

}

var operator() () {
 var type_in;
 var in0_in;
 var mode0_in;
 var output_out;
 var glang_in;
 return operator()(type_in, in0_in, mode0_in, output_out, glang_in);
}

var operator() (in type) {
 var in0_in;
 var mode0_in;
 var output_out;
 var glang_in;
 return operator()(type, in0_in, mode0_in, output_out, glang_in);
}

var operator() (in type, in in0) {
 var mode0_in;
 var output_out;
 var glang_in;
 return operator()(type, in0, mode0_in, output_out, glang_in);
}

var operator() (in type, in in0, in mode0) {
 var output_out;
 var glang_in;
 return operator()(type, in0, mode0, output_out, glang_in);
}

var operator() (in type, in in0, in mode0, out output) {
 var glang_in;
 return operator()(type, in0, mode0, output, glang_in);
}

};
efb_date date{mv};
//#endif
