//generated by exodus "compile holiday"
//#ifndef EXODUSDLFUNC_HOLIDAY_H
#define EXODUSDLFUNC_HOLIDAY_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_holiday;
class efb_holiday : public ExodusFunctorBase
{
public:

efb_holiday(MvEnvironment& mv) : ExodusFunctorBase("holiday", "exodusprogrambasecreatedelete_", mv) {}

efb_holiday& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode, io idate, in usercode, in userx, in marketcode, in market, in agp, out holidaytype, out workdate)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,io,in,in,in,in,in,out,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_holiday.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_holiday.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,idate,usercode,userx,marketcode,market,agp,holidaytype,workdate);

}

var operator() () {
 var mode_in;
 var idate_io;
 var usercode_in;
 var userx_in;
 var marketcode_in;
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode_in, idate_io, usercode_in, userx_in, marketcode_in, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode) {
 var idate_io;
 var usercode_in;
 var userx_in;
 var marketcode_in;
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate_io, usercode_in, userx_in, marketcode_in, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate) {
 var usercode_in;
 var userx_in;
 var marketcode_in;
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode_in, userx_in, marketcode_in, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode) {
 var userx_in;
 var marketcode_in;
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode, userx_in, marketcode_in, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode, in userx) {
 var marketcode_in;
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode, userx, marketcode_in, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode, in userx, in marketcode) {
 var market_in;
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode, userx, marketcode, market_in, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode, in userx, in marketcode, in market) {
 var agp_in;
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode, userx, marketcode, market, agp_in, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode, in userx, in marketcode, in market, in agp) {
 var holidaytype_out;
 var workdate_out;
 return operator()(mode, idate, usercode, userx, marketcode, market, agp, holidaytype_out, workdate_out);
}

var operator() (in mode, io idate, in usercode, in userx, in marketcode, in market, in agp, out holidaytype) {
 var workdate_out;
 return operator()(mode, idate, usercode, userx, marketcode, market, agp, holidaytype, workdate_out);
}

};
efb_holiday holiday{mv};
//#endif
