//generated by exodus "compile ../sys/mt2"
//#ifndef EXODUSDLFUNC_MT2_H
#define EXODUSDLFUNC_MT2_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_mt2;
class efb_mt2 : public ExodusFunctorBase
{
public:

efb_mt2(MvEnvironment& mv) : ExodusFunctorBase("mt2", "exodusprogrambasecreatedelete_", mv) {}

efb_mt2& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in type, in in0, in mode, out out0)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_mt2.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_mt2.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (type,in0,mode,out0);

}

var operator() () {
 var type_in;
 var in0_in;
 var mode_in;
 var out0_out;
 return operator()(type_in, in0_in, mode_in, out0_out);
}

var operator() (in type) {
 var in0_in;
 var mode_in;
 var out0_out;
 return operator()(type, in0_in, mode_in, out0_out);
}

var operator() (in type, in in0) {
 var mode_in;
 var out0_out;
 return operator()(type, in0, mode_in, out0_out);
}

var operator() (in type, in in0, in mode) {
 var out0_out;
 return operator()(type, in0, mode, out0_out);
}

};
efb_mt2 mt2{mv};
//#endif
