//generated by exodus "compile netlogin"
//#ifndef EXODUSDLFUNC_NETLOGIN_H
#define EXODUSDLFUNC_NETLOGIN_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_netlogin;
class efb_netlogin : public ExodusFunctorBase
{
public:

efb_netlogin(MvEnvironment& mv) : ExodusFunctorBase("netlogin", "exodusprogrambasecreatedelete_", mv) {}

efb_netlogin& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode0)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_netlogin.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_netlogin.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode0);

}

var operator() () {
 var mode0_in;
 return operator()(mode0_in);
}

};
efb_netlogin netlogin{mv};
//#endif
