//generated by exodus "compile number"
//#ifndef EXODUSDLFUNC_NUMBER_H
#define EXODUSDLFUNC_NUMBER_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_number;
class efb_number : public ExodusFunctorBase
{
public:

efb_number(MvEnvironment& mv) : ExodusFunctorBase("number", "exodusprogrambasecreatedelete_", mv) {}

efb_number& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in type, in input0, in ndecs0, out output)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_number.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_number.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (type,input0,ndecs0,output);

}

var operator() () {
 var type_in;
 var input0_in;
 var ndecs0_in;
 var output_out;
 return operator()(type_in, input0_in, ndecs0_in, output_out);
}

var operator() (in type) {
 var input0_in;
 var ndecs0_in;
 var output_out;
 return operator()(type, input0_in, ndecs0_in, output_out);
}

var operator() (in type, in input0) {
 var ndecs0_in;
 var output_out;
 return operator()(type, input0, ndecs0_in, output_out);
}

var operator() (in type, in input0, in ndecs0) {
 var output_out;
 return operator()(type, input0, ndecs0, output_out);
}

};
efb_number number{mv};
//#endif
