//generated by exodus "compile ../sys/sendmail"
//#ifndef EXODUSDLFUNC_SENDMAIL_H
#define EXODUSDLFUNC_SENDMAIL_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_sendmail;
class efb_sendmail : public ExodusFunctorBase
{
public:

efb_sendmail(MvEnvironment& mv) : ExodusFunctorBase("sendmail", "exodusprogrambasecreatedelete_", mv) {}

efb_sendmail& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in toaddress0, in ccaddress0, in subject0, in body0, in attachfilename0, in delete0, out errormsg, in replyto0=var(), in params0=var())
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,in,in,in,out,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_sendmail.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_sendmail.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (toaddress0,ccaddress0,subject0,body0,attachfilename0,delete0,errormsg,replyto0,params0);

}

var operator() () {
 var toaddress0_in;
 var ccaddress0_in;
 var subject0_in;
 var body0_in;
 var attachfilename0_in;
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0_in, ccaddress0_in, subject0_in, body0_in, attachfilename0_in, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0) {
 var ccaddress0_in;
 var subject0_in;
 var body0_in;
 var attachfilename0_in;
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0_in, subject0_in, body0_in, attachfilename0_in, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0, in ccaddress0) {
 var subject0_in;
 var body0_in;
 var attachfilename0_in;
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0, subject0_in, body0_in, attachfilename0_in, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0, in ccaddress0, in subject0) {
 var body0_in;
 var attachfilename0_in;
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0, subject0, body0_in, attachfilename0_in, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0, in ccaddress0, in subject0, in body0) {
 var attachfilename0_in;
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0, subject0, body0, attachfilename0_in, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0, in ccaddress0, in subject0, in body0, in attachfilename0) {
 var delete0_in;
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0, subject0, body0, attachfilename0, delete0_in, errormsg_out, replyto0_in, params0_in);
}

var operator() (in toaddress0, in ccaddress0, in subject0, in body0, in attachfilename0, in delete0) {
 var errormsg_out;
 var replyto0_in;
 var params0_in;
 return operator()(toaddress0, ccaddress0, subject0, body0, attachfilename0, delete0, errormsg_out, replyto0_in, params0_in);
}

};
efb_sendmail sendmail{mv};
//#endif
