//generated by exodus "compile ../sys/stop"
//#ifndef EXODUSDLFUNC_STOP_H
#define EXODUSDLFUNC_STOP_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_stop;
class efb_stop : public ExodusFunctorBase
{
public:

efb_stop(MvEnvironment& mv) : ExodusFunctorBase("stop", "exodusprogrambasecreatedelete_", mv) {}

efb_stop& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode, in time, in date, out buffer, out msg)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,out,out);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_stop.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_stop.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,time,date,buffer,msg);

}

var operator() () {
 var mode_in;
 var time_in;
 var date_in;
 var buffer_out;
 var msg_out;
 return operator()(mode_in, time_in, date_in, buffer_out, msg_out);
}

var operator() (in mode) {
 var time_in;
 var date_in;
 var buffer_out;
 var msg_out;
 return operator()(mode, time_in, date_in, buffer_out, msg_out);
}

var operator() (in mode, in time) {
 var date_in;
 var buffer_out;
 var msg_out;
 return operator()(mode, time, date_in, buffer_out, msg_out);
}

var operator() (in mode, in time, in date) {
 var buffer_out;
 var msg_out;
 return operator()(mode, time, date, buffer_out, msg_out);
}

var operator() (in mode, in time, in date, out buffer) {
 var msg_out;
 return operator()(mode, time, date, buffer, msg_out);
}

};
efb_stop stop{mv};
//#endif
