//generated by exodus "compile ../med/calcbill"
//#ifndef EXODUSDLFUNC_CALCBILL_H
#define EXODUSDLFUNC_CALCBILL_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_calcbill;
class efb_calcbill : private ExodusFunctorBase
{
public:

efb_calcbill(MvEnvironment& mv) : ExodusFunctorBase("calcbill", "exodusprogrambasecreatedelete_", mv) {}

efb_calcbill& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (io grossbill, in spec, in extras2, in unused, io msg, in roundingx, io sizemult, io amounts)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(io,in,in,in,io,in,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_calcbill.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_calcbill.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (grossbill,spec,extras2,unused,msg,roundingx,sizemult,amounts);

}

};
efb_calcbill calcbill{mv};
//#endif
