#include <exodus/common.h>

#define ab_common_no 11

commoninit(ab,ab_common_no)

	var maxnlevels;//num
	var maxncols;//num
	var nparams;//num
	var coln;//num
	var seqid;
	var msg;
	var atlbtl;
	var orighead;
	var minyear;//num
	var maxyear;//num
	var ncols;//num
	var lev;//num
	var nlevels;//num
	var pagelev;//num
	var numberfmt;
	var tempdictids;
	var dictrec;
	var tempdictid;
	var colhead1;
	var colhead2;
	var rec;
	var nrecs;//num
	var dictanalysis;
	var invact;//num
	var designid;
	var colparams;
	var period;
	var currperiodno;//num
	var year;//num
	var type;
	var pageclass;
	var recn;//num
	var leveltitles;
	var nvisible;//num
	var paramn;//num
	var colinfo1;
	var colinfo2;
	var colinfo3;
	var reqtype;
	var notrequired;
	var colactivites;
	var activitycodes;
	var periodn;//num
	var nperiods;//num
	var oneperiod;//num
	var onperiod;
	var colfromperiod;
	var coltoperiod;
	var colfromyear;
	var coltoyear;
	var splitperiods;
	var nsplit;
	var splitn;//num
	var newcoln;//num
	var totspan1;//num
	var span;//num
	var totspan2;//num
	var classx;
	var linenox;//num
	var lev2;
	var nactivities;//num
	var activityn;//num
	var key;
	var coln2;
	var nonoptypecodes;
	var nonreqtypecodes;
	var accounts;
	dim cols;
	dim levelx;
	dim code;
	dim newcode;
	dim desc;
	dim newdesc;
	dim line;
	dim ntots;
	dim analrec;

commonexit(ab,ab_common_no)
