#include <exodus/library.h>
libraryinit()

// nextkey(params [, mode2])
// params: actfile:seqkey:keyfile:prefix  ("% " = number slot)
//
// mode2 omitted/falsy — next free (walk *forward* past occupied; lock; may bump seq)
// mode2 == 1         — previous: key for seq-1, no existence check (historic)
// mode2 == 2         — previous existing: from seq walk *back* until a key exists
//                      (max 10, skip holes); read-only; "" if none

var previous;  // num

func main(in mode, in previous0 = "") {
	previous = previous0.or_default("");

	var result = "";
	ANS		   = "";
	var keyx   = "";

	var actfilename = mode.field(":", 1);
	let seqkey		= mode.field(":", 2);
	let keyfilename = mode.field(":", 3);
	let prefix		= mode.field(":", 4);

	if (actfilename == "") {
		let temp = seqkey.index(".SK");
		if (temp) {
			actfilename = seqkey.first(temp - 1);
		} else {
			actfilename = keyfilename;
		}
	}

	var keyfile;
	if (not keyfile.open(keyfilename, "")) {
		call note(lasterror());
		return ANS;
	}

	var actfile;
	if (not actfile.open(actfilename, "")) {
		call note(lasterror());
		return ANS;
	}

	// lock the source of numbers
	var buffer = "";
lockit:
	if (not lockrecord(keyfilename, keyfile, seqkey)) {
		var temp = keyfilename;
		if (temp.ends("S")) {
			temp.cutter(1);
		}
		if (not buffer) {
			call note("WAITING TO GET THE NEXT " ^ temp ^ " NUMBER|PRESS ESCAPE TO EXIT.", "UB", buffer);
		}
		if (esctoexit()) {
			call note("", "DB", buffer);
			return "";
		}
		call ossleep(1000 * 1);
		goto lockit;
	}
	if (buffer) {
		call note("", "DB", buffer);
	}

	// get the initial next number
	var nextno;
	if (not nextno.read(keyfile, seqkey)) {
		// previous / previous-existing: no sequence → no key (do not invent seq)
		if (previous) {
			unlockrecord(keyfilename, keyfile, seqkey);
			return ANS;
		}
		if (actfilename == "VOUCHERS") {
			// actually voucher numbers are not generated by nextkey (see acc.params<17>)
			nextno = 1;
		} else {
			// better starting point than 1 (more sortable and less confusing)
			nextno = 1000;
		}

		nextno.write(keyfile, seqkey);
	}
	nextno = nextno.f(1);

	// ── 2 = previous existing: from seq walk back until key exists ──
	if (previous == 2) {
		result = nextno;
		for (var ntry = 1; ntry <= 10; ++ntry) {
			if (result < 1)
				break;

			keyx = result;
			if (prefix) {
				keyx = prefix;
				if (prefix.contains("%"))
					keyx.replacer("%", result);
				else
					keyx ^= result;
			}

			if (var().read(actfile, keyx)) {
				ANS = keyx;
				unlockrecord(keyfilename, keyfile, seqkey);
				return keyx;
			}
			result -= 1;
		}

		unlockrecord(keyfilename, keyfile, seqkey);
		ANS	 = "";
		return ANS;
	}

	// ── 1 = previous (historic): seq-1, no existence check ──
	if (previous) {
		nextno -= 1;
	}

	// ── next free (or previous key built below): walk forward only when allocating ──
	keyx = "";
	if (nextno != "") {
		result		   = nextno;
		var currnextno = result;
		var notok	   = 1;

checkrec:

		// make the keyx from RESULT and PREFIX
		keyx = result;
		if (prefix) {
			keyx = prefix;
			if (prefix.contains("%")) {
				keyx.replacer("%", result);
			} else {
				keyx ^= result;
			}
		}

		if (previous) {
			// mode 1: accept seq-1 key without read/lock
			notok = 0;
		} else {
			var temp;
			if (temp.read(actfile, keyx)) {
				if (notok == 1) {
					currnextno += 1;
				}
			} else {
				if (notok == 1) {
					if (currnextno > nextno) {
						currnextno.writef(keyfile, seqkey, 1);
					}
					notok = 2;
				}
				if (lockrecord(actfilename, actfile, keyx)) {
					notok = 0;
				}
			}
		}

		if (notok) {
			result += 1;
			goto checkrec;
		}

		unlockrecord(actfilename, actfile, keyx);
	}

	unlockrecord(keyfilename, keyfile, seqkey);

	ANS = keyx;
	return keyx;
}

}; // libraryexit()
