#!/bin/bash

#to run installexodus-postgresql you need to be root or run it as sudo or
#or be able to login to user postgres (often disabled)

if [ -d /var/lib/pgsql ] && [ ! -f /var/lib/pgsql/data/pg_hba.conf ]; then
/etc/init.d/postgresql initdb
/etc/init.d/postgresql start
/sbin/chkconfig postgresql on
fi

#start/restart it in case it is not running
for PGSERVICE in `ls /etc/init.d/postgresql* 2>/dev/null`; do $PGSERVICE restart || : ; done

#run the actual postgres configuration script as su postgres
#su postgres installexodus-postgresql2
su postgres ${0}2

#reload the new postgresql configuration
for PGSERVICE in `ls /etc/init.d/postgresql* 2>/dev/null`; do $PGSERVICE reload || : ; done


