#!/bin/bash

#to run installexodus-postgresql you need to be root or run it as sudo or
#or be able to login to user postgres (often disabled)

#ensure postgresql is configured and running (not just installed and waiting)
for PGSERVICE in `ls /etc/init.d/postgresql* 2>/dev/null`; do $PGSERVICE reload || : ; done

#run the actual postgres configuration script as su postgres
#su postgres installexodus-postgresql2
su postgres ${0}2

#reload the new postgresql configuration
for PGSERVICE in `ls /etc/init.d/postgresql* 2>/dev/null`; do $PGSERVICE reload || : ; done


