#!/bin/bash
set -eux

: ========================
: Copy a postgres database
: ========================
:
: 'Syntax is ./copy_db <FROM_DBNAME> <TO_DNAME> [DELETE]'
:
	FROM_DB_CODE=${1:?<FROM_DBNAME> argument is required.}
	TO_DB_CODE=${2:?<TO_DBNAME> argument is required.}
#	OPTIONS=$3
    OPTIONS=${3:-}

:
: Check Syntax
: ============
:
	if [ -z "FROM_DB_CODE"  -o  -z "$TO_DB_CODE" ]; then
		set +x
		echo 'Syntax is wrong. Cannot continue.'
		exit 1
	fi

:
: Shutdown $TO_DB_CODE service if exists
: ========================================
:
	./service ${TO_DB_CODE} stop && RESTART_REQUIRED=yes || RESTART_REQUIRED=no

:
: Give it some time to stop
: =========================
:
	sleep 5

:
: Delete any existing $TO_DB_CODE database
: ======================================================
:
	if [ "$OPTIONS" = "DELETE" ]; then
		#sudo -u postgres dropdb $TO_DB_CODE || true
		for TRY in 1 2 3; do
			dbdelete $TO_DB_CODE && break || true
		done
	fi

:
: Copy $FROM_DB_CODE to $TO_DB_CODE
: ====================================
:
	#sudo -u postgres createdb -O exodus -T $FROM_DB_CODE $TO_DB_CODE
	dbcopy $FROM_DB_CODE $TO_DB_CODE

:
: Restart $TO_DB_CODE service if exists
: =======================================
:
	if [ $RESTART_REQUIRED = yes ]; then
		./service ${TO_DB_CODE} start || true
	fi

:
: Finished copy_db $1 in $(($SECONDS / 60)) minutes and $(($SECONDS % 60)) seconds.
: =======================================================
