#!/bin/bash
set -euxo pipefail

: =======================================
: Create/update an apache site for exodus
: =======================================
:
: 'Syntax is ./create_site <FQDN> "[HOST_DIR]" "[DB_CODE]" [SITE_NAME_PREFIX]'
:
: 'Example:  ./create_site exodus'
:
: 'Example:  ./create_site test "" "" t-'
:
	FQDN=${1:?FQDN is required. Can be just host name if self certified https cert}
	HOST_DIR=${2:-}
	DB_CODE=${3:-}
	SITE_PREFIX=${4-}

:
: Config
: ======
:
#	FQDN=exodus.hosts.neosys.com
	HOST_NAME=${FQDN%%.*} # first word of FQDN e.g. exodus
	DOMAIN_NAME=${FQDN#*.} # remainder of FQDN e.g. hosts.exodus.com
	SUFFIXED_FQDN=${SITE_PREFIX}$FQDN
:
: Defaults
:
	DOMAIN_NAME=${DOMAIN_NAME:-exodus.com}
	HOST_DIR=${HOST_DIR:-$HOST_NAME}
	DB_CODE=${DB_CODE:-$HOST_NAME}

:
: Check current directory
: =======================
:
	EXODUS=`pwd`
	test -f $EXODUS/install_www_apt.sh || ( echo Must be run in exodus install dir without path && exit )

:
: If installing into /root/ then allow cd into /root - but no read access of course
: =================================================================================
:
	if [ ${EXODUS:0:6} = /root/ ]; then
		chmod o+x /root
	fi

:
: Function to call apt-get repeatedly in case of error
: ----------------------------------------------------
:
function APT_GET {
:
	STARTED=$SECONDS
	while [[ $(($SECONDS-$STARTED)) -lt 600 ]]; do
:
: Retry apt-get. $(($SECONDS-$STARTED)) secs.
: -------------------
:
		# /dev/null to stop error causing random hang until timeout
		# with apt process stuck on tcsetattr call. see gdb -p 9999
		if timeout 120s $* < /dev/null; then
			break
		fi
		sleep 5
	done;
}

:
: Install apache and php
: ======================
:
: Note that apache/mods may be already installed but not enabled
:
	APT_GET sudo apt-get install -y apache2 libapache2-mod-php php php-xml
:
: Dump mods available and enabled
:
#	sudo ls -l /etc/apache2/mods-available/
	sudo ls -l /etc/apache2/mods-enabled/
:
: Ensure that  required mods are actually enabled
:
	sudo a2enmod rewrite ssl php*
:
: Restart apache
:
	sudo systemctl restart apache2

:
: Configure php.ini - increase limits
: ===================================
:
	PHP_CONF_DIR=`php --ini|grep '/etc/php/[0-9.]*' -o | head -n1`
	PHP_EXODUS_INI=${PHP_CONF_DIR}/apache2/conf.d/00-exodus.ini
:
#	sudo ls -l $PHP_CONF_DIR -r
#	sudo php --ini
##	sudo find /etc/ -name php.ini | grep 'apache2' || true
#	sudo find /etc/ -name php.ini || true
#	sudo find /etc/ -name xml.ini || true

:
	if [ ! -e $PHP_EXODUS_INI ]; then
#		(
			# sudo cat > ${PHP_EXODUS_INI} <<-V0G0N
			# Use sudo dd because sudo doesnt work with redirection
			# sudo acts after the redirection is established
			sudo dd of=${PHP_EXODUS_INI} status=none <<-V0G0N
				[exodus]
				; defaults
				; max_execution_time = 30
				; upload_max_filesize = 2M
				; post_max_size = 8M

				max_execution_time = 606
				upload_max_filesize = 10M
				post_max_size = 10M
			V0G0N
#		) || (
#: =====================================================
#: Error: Could not configure $PHP_EXODUS_INI. See above
#: =====================================================
#			if [[ -n ${GITHUB_WORKSPACE:-} ]]; then
#:
#: Skipping to allow building on github
#: which seems to be missing /etc/php/N.N/apache2/conf.d
#: TODO resolve missing apache/php packages?
#:
#				true
#			else
#				false
#			fi
#		)
	fi

:
: Enable module to add headers
: ============================
:
	sudo a2enmod headers

:
: Enable module for case insensitivity in images folder
: =====================================================
:
	sudo a2enmod speling

:
: Ensure setfacl is installed
: ===========================
:
	which setfacl || APT_GET sudo apt-get install -y acl

:
: Create link from hostname dir to host dir if different
: ======================================================
:
	if [ "$HOST_NAME" != "$HOST_DIR" ]; then
		ln -snf ~/hosts/$HOST_DIR ~/hosts/$HOST_NAME
	fi
                             :
: Make site directories like ~/hosts/demo/{work,data,images}
: ==========================================================
:
	SITEDIR=~/hosts/$HOST_DIR
	for SUBHOST_DIR in work data images; do
		mkdir -p $SITEDIR/$SUBHOST_DIR
		chmod a+srw $SITEDIR/$SUBHOST_DIR
	done

:
: Ensure directory permissions on data/$DB_CODE
: ==============================================
:
: KEEP IN SYNC. SIMILAR code in create_site, create_service and generalproxy.cpp
:
    DB_DIR=~/hosts/$HOST_DIR/data/$DB_CODE
    mkdir -p $DB_DIR
    chmod a+srw $DB_DIR
    setfacl -d -m g::rw $DB_DIR

:
: Link to exodus www
: ==================
:
	rm $SITEDIR/www -rf
	ln -snf ~/exodus/service/www/ $SITEDIR/www

:
: Configure Certificates
: ======================
:
: Check for cert/key for FQDN $FQDN or wildkey cert/key for domain name $DOMAIN_NAME
:
	for DN in $FQDN $DOMAIN_NAME; do
:
: Check if LetsEncrypt cert/key is available "'$DN'"
:
		LE_PUBCERT=/etc/letsencrypt/live/$DN/fullchain.pem
		LE_PRIVKEY=/etc/letsencrypt/live/$DN/privkey.pem
		if sudo test -f $LE_PUBCERT && sudo test -f $LE_PRIVKEY; then
:
: Use LetsEncrypt cert/key "'$DN'"
:
			PUBCERT=$LE_PUBCERT
			PRIVKEY=$LE_PRIVKEY
			break;
		fi
	done

:
: Check if cert/key found for FQDN or domain name
:
	if [[ -z ${PUBCERT:-} ]]; then
:
: Use snakeoil self signed certificate and key
:
		PUBCERT=/etc/ssl/certs/ssl-cert-snakeoil.pem
		PRIVKEY=/etc/ssl/private/ssl-cert-snakeoil.key
	fi

:
: Provide a fixed link to the chosen cert and key
:
	PUBCERT_LINK=/etc/ssl/certs/$HOST_NAME-cert.pem
	PRIVKEY_LINK=/etc/ssl/private/$HOST_NAME-key.pem
:
	sudo ln -snf $PUBCERT $PUBCERT_LINK
	sudo ln -snf $PRIVKEY $PRIVKEY_LINK

:
: Create an Apache virtual site
: =============================
:
	APACHE_SITE_CONF=/etc/apache2/sites-available/$HOST_NAME.conf
	TMPFILE=$(mktemp /tmp/create_site.XXXXXXXX)
	sudo dd of=${TMPFILE} status=none <<-V0G0N
		# generated by ~/exodus/service/create_site
		#$HOST_NAME
		ServerSignature Off
		ServerTokens Prod
		<VirtualHost *:443>
		    #SSLCertificateFile    /etc/ssl/certs/$HOST_NAME-cert.pem
		    #SSLCertificateKeyFile /etc/ssl/private/$HOST_NAME-key.pem
		    SSLCertificateFile    $PUBCERT_LINK
		    SSLCertificateKeyFile $PRIVKEY_LINK
		    SSLEngine on
		    ServerName $SUFFIXED_FQDN
		    DocumentRoot $HOME/hosts/$HOST_DIR/www/
		    Alias /data/ $HOME/hosts/$HOST_DIR/data/
		    Alias /images/ $HOME/hosts/$HOST_DIR/images/
		    #emerg/alert/crit/error/warn/notice/info/debug/trace1/.../trace8
		    LogLevel info
		    AddDefaultCharset utf-8
		    Header set Cache-Control "max-age=300, public"
		    <Directory $HOME/hosts/$HOST_DIR/www/>
		        Options +FollowSymLinks
		        AllowOverride All
		        Require all granted
		    </Directory>
		    <Directory $HOME/hosts/$HOST_DIR/data/>
		        Options +FollowSymLinks
		        AllowOverride All
		        Require all granted
		    </Directory>
		    <Directory $HOME/hosts/$HOST_DIR/images/>
		        #case insensitivity
		        CheckSpelling On
		        CheckCaseOnly On
		        Options +FollowSymLinks
		        AllowOverride All
		        Require all granted
		    </Directory>
		</VirtualHost>
		V0G0N
	sudo mv $TMPFILE $APACHE_SITE_CONF

:
: Disable exodus sites
: ====================
:
	sudo a2dissite exodus exodus-ssl || true
	sudo apache2ctl configtest
	sudo apache2ctl restart

:
: Enable the site and restart apache - $HOST_NAME
: ==================================
:
	sudo a2ensite $HOST_NAME
	sudo apache2ctl configtest
	sudo apache2ctl restart

:
: CREATED https://$SUFFIXED_FQDN
: ===============================
