#!/bin/bash
set -eux

: =======================
: Delete a NEOSYS service
: =======================
:
:   'Syntax is ./delete_service <APP_CODE> <HOST_DIR> "[DB_CODE]" {live|test}'
:
:   'e.g.      ./delete_service exo exodus "" live'
:   'e.g.      ./delete_service agy watermelon watermelon test'
:

    APP_CODE=${1:?<APP_CODE> argument is required.}
    HOST_DIR=${2:?<HOST_DIR> argument is required.}
    DB_CODE=${3:-${HOST_DIR}}
    LIVE_OR_TEST=${4:?live|test argument is required.}
:
    SERVICE_CODE=${APP_CODE}_$LIVE_OR_TEST
    FULL_SERVICE_CODE=$SERVICE_CODE@${DB_CODE}

:
: Check syntax
: ============
:
    if [ $LIVE_OR_TEST != live -a $LIVE_OR_TEST != test ]; then
:       'Syntax error'
        exit 1
    fi

:
:
: Stop and disable the service
: ============================
:
	sudo systemctl stop $FULL_SERVICE_CODE || true
	sudo systemctl disable $FULL_SERVICE_CODE || true
#:
#: NO. BECAUSE IT IS A TEMPLATE FOR OTHER NEOSYS SERVICES
#: Remove the service definition file
#: ==================================
#:
#:	sudo rm /etc/systemd/system/$SERVICE_CODE.service || true
#:

:
: Remove any log files
: ====================
:
:	'sudo rm -f /etc/rsyslog.d/$SERVICE_CODE.conf || true'
:	'sudo rm -f /var/log/$PREFIX/$DB_CODE.log || true'

:
: Notify the daemon
: =================
:
        if [ -z ${DOALL:-} ]; then
                sudo systemctl daemon-reload 
        else
                touch /tmp/systemctl.daemon-reload.required
        fi

:
: $FULL_SERVICE_CODE service deleted.
: ===================================

