#!/bin/bash
set -euxo pipefail
PS4='+ [./delete_site:$LINENO ${HOST_NAME:-${1-}} ${SECONDS}s] '

: ─────────────────────────────────────────────────────────────────────────────────
: Delete an apache site
: ─────────────────────────────────────────────────────────────────────────────────
: 'Syntax is ./delete_site HOST_NAME [SITE_DIR]'
:
	HOST_NAME=${1:?HOST_NAME argument is required.}
	SITE_DIR=${2:-$1}

	SITE_CODE=$HOST_NAME
:
: Disable the site
: ────────────────────────────────────────
	a2dissite $SITE_CODE || true
:
: Remove the site
: ────────────────────────────────────────
	rm /etc/apache2/sites-available/$SITE_CODE.conf || true

	( apache2ctl configtest && apache2ctl restart ) || true

: Remove links to certificates
: ────────────────────────────
: /etc/letsencrypt/live/hosts.neosys.com/fullchain.pem
: /etc/ssl/private/test-key.pem

    rm /etc/ssl/certs/${HOST_NAME}.pem       || true
    rm /etc/ssl/private/${HOST_NAME}-key.pem || true

: rm ~/hosts/$SITE_DIR -r || true
:
: ────────────────────────────────────────
: Finished delete_site - DELETED Apache site $SITE_CODE
: ────────────────────────────────────────
