#!/bin/bash
set -eu

:
: Email with optional attachment via local sendmail
: =================================================
:
	TOEMAIL="$1"		#multiple email addressses can separated by ;

	FULL_FILENAME="$2"	#absolute path to optional attachment

	HEADERS="$3"		#must include EVERYTHING
	#From:test@neosys.com
	#Reply-to: dev@neosys.com
	#To:dev@neosys.com;dev2@neosys.com
	#Cc: aaa@neosys.com;bbb@neosys.com
	#Subject:EXODUS: Media Diary (to:TBQBB)
	#X-Auto-Response-Suppress: RN, NRN, OOF
	#Precedence: bulk

	if [ -n "$FULL_FILENAME" ]; then
		FILENAME=${FULL_FILENAME##*/}
		MIMETYPE=$(file --mime-type "$FULL_FILENAME" | sed 's/.*: //')
	fi

	{

		cat <<-V0G0N
			$HEADERS

		V0G0N

		if [ -n "$FULL_FILENAME" ]; then
			cat <<-V0G0N
				MIME-Version: 1.0
				Content-Type: multipart/mixed;
				 boundary="------------5723BF0875E398DEC19D9328"
				Content-Language: en-GB

				This is a multi-part message in MIME format.
				--------------5723BF0875E398DEC19D9328
				Content-Type: text/plain; charset=utf-8; format=flowed
				Content-Transfer-Encoding: 7bit

				--------------5723BF0875E398DEC19D9328
				Content-Type: $MIMETYPE;
				 name="$FILENAME"
				Content-Transfer-Encoding: base64
				Content-Disposition: attachment;
				 filename="$FILENAME"

			V0G0N

			openssl base64 -in $FULL_FILENAME

			cat <<-V0G0N
				--------------5723BF0875E398DEC19D9328--
				V0G0N
		fi

		cat

	} | sendmail -t $TOEMAIL
