#!/bin/bash
set -eu

: =================================================================================
: Service commands start, stop, restart, reload, status, is-active, enable, disable
: =================================================================================
:
: 'Syntax is ./service DB_CODE start|stop|restart|reload|status|is-active|enable|disable [test|live]'
:
: 'Environment variable: $APP_CODE Defaults to "exo". Used for prefix on services'
:
: 'Output can be active, inactive, failed'
:
	APP_CODE=${APP_CODE:-exo}
:
	DB_CODE=${1:?DB_CODE argument is required}
	CMD=${2:?Action [start|stop|etc.] argument is required}
	LIVE_OR_TEST=${3:-}

:
: LIVE
: ====
:
	if [ "$LIVE_OR_TEST" != "test" ]; then
		sudo systemctl $CMD ${APP_CODE}_live@$DB_CODE
	fi

:
: TEST
: ====
:
	if [ "$LIVE_OR_TEST" != "live" ]; then
		sudo systemctl $CMD ${APP_CODE}_test@$DB_CODE
	fi

