#!/bin/bash
set -euxo pipefail
PS4='+ [./test ${DB_CODE:-${1-}} ${SECONDS}s] '

: ─────────────────────────────────────────────────────────────────────────────────
: Stop a background test service and run it in the foreground
: ─────────────────────────────────────────────────────────────────────────────────
:	'Syntax is ./test [DBNAME]'
:
:	'Example:  ./test           #uses test_test database'
:
:	'Example:  ./test centauro  #uses centauro_test database'
:

	export DB_CODE=${1:-test}		#default to the test_test database

	./run ${DB_CODE%_test}_test 	#remove superfluous _test and append _test
