//generated by exodus "compile multiply"
//#ifndef EXODUSDLFUNC_MULTIPLY_H
#define EXODUSDLFUNC_MULTIPLY_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_multiply;
class efb_multiply : public ExodusFunctorBase
{
public:

efb_multiply(MvEnvironment& mv) : ExodusFunctorBase("multiply", "exodusprogrambasecreatedelete_", mv) {}

efb_multiply& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in multipliers, in multiplicand, in sep)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_multiply.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_multiply.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (multipliers,multiplicand,sep);

}

var operator() () {
 var multipliers_in;
 var multiplicand_in;
 var sep_in;
 return operator()(multipliers_in, multiplicand_in, sep_in);
}

var operator() (in multipliers) {
 var multiplicand_in;
 var sep_in;
 return operator()(multipliers, multiplicand_in, sep_in);
}

var operator() (in multipliers, in multiplicand) {
 var sep_in;
 return operator()(multipliers, multiplicand, sep_in);
}

};
efb_multiply multiply{mv};
//#endif
