//generated by exodus "compile ../add/rtp57"
//#ifndef EXODUSDLFUNC_RTP57_H
#define EXODUSDLFUNC_RTP57_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_rtp57;
class efb_rtp57 : private ExodusFunctorBase
{
public:

efb_rtp57(MvEnvironment& mv) : ExodusFunctorBase("rtp57", "exodusprogrambasecreatedelete_", mv) {}

efb_rtp57& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in code, in fs, io handle, in keyorfilename, in fmc, io record, io status)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,io,in,in,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_rtp57.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_rtp57.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (code,fs,handle,keyorfilename,fmc,record,status);

}

var operator() () {
 var code_in;
 var fs_in;
 var handle_io;
 var keyorfilename_in;
 var fmc_in;
 var record_io;
 var status_io;
 return operator()(code_in, fs_in, handle_io, keyorfilename_in, fmc_in, record_io, status_io);
}

var operator() (in code) {
 var fs_in;
 var handle_io;
 var keyorfilename_in;
 var fmc_in;
 var record_io;
 var status_io;
 return operator()(code, fs_in, handle_io, keyorfilename_in, fmc_in, record_io, status_io);
}

var operator() (in code, in fs) {
 var handle_io;
 var keyorfilename_in;
 var fmc_in;
 var record_io;
 var status_io;
 return operator()(code, fs, handle_io, keyorfilename_in, fmc_in, record_io, status_io);
}

var operator() (in code, in fs, io handle) {
 var keyorfilename_in;
 var fmc_in;
 var record_io;
 var status_io;
 return operator()(code, fs, handle, keyorfilename_in, fmc_in, record_io, status_io);
}

var operator() (in code, in fs, io handle, in keyorfilename) {
 var fmc_in;
 var record_io;
 var status_io;
 return operator()(code, fs, handle, keyorfilename, fmc_in, record_io, status_io);
}

var operator() (in code, in fs, io handle, in keyorfilename, in fmc) {
 var record_io;
 var status_io;
 return operator()(code, fs, handle, keyorfilename, fmc, record_io, status_io);
}

var operator() (in code, in fs, io handle, in keyorfilename, in fmc, io record) {
 var status_io;
 return operator()(code, fs, handle, keyorfilename, fmc, record, status_io);
}

};
efb_rtp57 rtp57{mv};
//#endif
