//generated by exodus "compile ../add/xselect"
//#ifndef EXODUSDLFUNC_XSELECT_H
#define EXODUSDLFUNC_XSELECT_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_xselect;
class efb_xselect : private ExodusFunctorBase
{
public:

efb_xselect(MvEnvironment& mv) : ExodusFunctorBase("xselect", "exodusprogrambasecreatedelete_", mv) {}

efb_xselect& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in cmd)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_xselect.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_xselect.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (cmd);

}

var operator() () {
 var cmd_in;
 return operator()(cmd_in);
}

};
efb_xselect xselect{mv};
//#endif
