//generated by exodus "compile budgetsheetsubs"
//#ifndef EXODUSDLFUNC_BUDGETSHEETSUBS_H
#define EXODUSDLFUNC_BUDGETSHEETSUBS_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_budgetsheetsubs;

//a member function with the right arguments, returning a var or void
var budgetsheetsubs(in mode)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_budgetsheetsubs.pmemberfunction_==NULL)
  efb_budgetsheetsubs.init("budgetsheetsubs","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_budgetsheetsubs.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_budgetsheetsubs.pmemberfunction_)))
  (mode);

}
//#endif
