//generated by exodus "compile ../agy/dict_job_types"
//#ifndef EXODUSDLFUNC_DICT_JOB_TYPES_H
#define EXODUSDLFUNC_DICT_JOB_TYPES_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_dict_job_types;
class efb_dict_job_types : private ExodusFunctorBase
{
public:

efb_dict_job_types(MvEnvironment& mv) : ExodusFunctorBase("dict_job_types", "exodusprogrambasecreatedelete_", mv) {}

efb_dict_job_types& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() ()
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)();

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_dict_job_types.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_dict_job_types.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  ();

}

};
efb_dict_job_types dict_job_types{mv};
//#endif
