//generated by exodus "compile ../agy/getagp"
//#ifndef EXODUSDLFUNC_GETAGP_H
#define EXODUSDLFUNC_GETAGP_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_getagp;
class efb_getagp : private ExodusFunctorBase
{
public:

efb_getagp(MvEnvironment& mv) : ExodusFunctorBase("getagp", "exodusprogrambasecreatedelete_", mv) {}

efb_getagp& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in agpparams, in period0)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_getagp.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_getagp.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (agpparams,period0);

}

};
efb_getagp getagp{mv};
//#endif
