//generated by exodus "compile ../agy/validcode3"
//#ifndef EXODUSDLFUNC_VALIDCODE3_H
#define EXODUSDLFUNC_VALIDCODE3_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_validcode3;
class efb_validcode3 : private ExodusFunctorBase
{
public:

efb_validcode3(MvEnvironment& mv) : ExodusFunctorBase("validcode3", "exodusprogrambasecreatedelete_", mv) {}

efb_validcode3& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in marketcodex, in suppliercodex, in vehiclecodex, io vehicles, io msg)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,in,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_validcode3.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_validcode3.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (marketcodex,suppliercodex,vehiclecodex,vehicles,msg);

}

};
efb_validcode3 validcode3{mv};
//#endif
