//generated by exodus "compile ../med/plansubs5"
//#ifndef EXODUSDLFUNC_PLANSUBS5_H
#define EXODUSDLFUNC_PLANSUBS5_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_plansubs5;
class efb_plansubs5 : public ExodusFunctorBase
{
public:

efb_plansubs5(MvEnvironment& mv) : ExodusFunctorBase("plansubs5", "exodusprogrambasecreatedelete_", mv) {}

efb_plansubs5& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_plansubs5.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_plansubs5.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode);

}

var operator() () {
 var mode_in;
 return operator()(mode_in);
}

};
efb_plansubs5 plansubs5{mv};
//#endif
