//generated by exodus "compile ../fin/valacc"
//#ifndef EXODUSDLFUNC_VALACC_H
#define EXODUSDLFUNC_VALACC_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_valacc;
class efb_valacc : private ExodusFunctorBase
{
public:

efb_valacc(MvEnvironment& mv) : ExodusFunctorBase("valacc", "exodusprogrambasecreatedelete_", mv) {}

efb_valacc& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (io mode, io is, io isorig, in validaccs, io msg, in acctype0)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(io,io,io,in,io,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_valacc.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_valacc.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,is,isorig,validaccs,msg,acctype0);

}

};
efb_valacc valacc{mv};
//#endif
