#ifndef ExodusFunctorS4_H
#define ExodusFunctorS4_H

//generated by genfunctors.cpp

#include <exodus/mvfunctor.h>

template<class T1, class T2, class T3, class T4>
class ExodusFunctorS4 : private ExodusFunctorBase
{
public:
 ExodusFunctorS4(const std::string libname,const std::string funcname)
	: ExodusFunctorBase(libname,funcname){}

 void operator() ()
 {
	checkload();
	typedef void (*ExodusDynamic)(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
	 ((ExodusDynamic) _pfunction)(T1(), T2(), T3(), T4());
	return;
 }

 void operator() (T1 arg1)
 {
	checkload();
	typedef void (*ExodusDynamic)(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
	 ((ExodusDynamic) _pfunction)(arg1, T2(), T3(), T4());
	return;
 }

 void operator() (T1 arg1, T2 arg2)
 {
	checkload();
	typedef void (*ExodusDynamic)(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
	 ((ExodusDynamic) _pfunction)(arg1, arg2, T3(), T4());
	return;
 }

 void operator() (T1 arg1, T2 arg2, T3 arg3)
 {
	checkload();
	typedef void (*ExodusDynamic)(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
	 ((ExodusDynamic) _pfunction)(arg1, arg2, arg3, T4());
	return;
 }

 void operator() (T1 arg1, T2 arg2, T3 arg3, T4 arg4)
 {
	checkload();
	typedef void (*ExodusDynamic)(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
	 ((ExodusDynamic) _pfunction)(arg1, arg2, arg3, arg4);
	return;
 }

};
#endif
