//generated by exodus "compile shadowmfs"
//#ifndef EXODUSDLFUNC_SHADOWMFS_H
#define EXODUSDLFUNC_SHADOWMFS_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_shadowmfs;
class efb_shadowmfs : public ExodusFunctorBase
{
public:

efb_shadowmfs(MvEnvironment& mv) : ExodusFunctorBase("shadowmfs", "exodusprogrambasecreatedelete_", mv) {}

efb_shadowmfs& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
        return (*this);
}

//a member function with the right arguments, returning a var or void
var operator() (in mode, in options)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_shadowmfs.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_shadowmfs.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,options);

}

var operator() () {
 var mode_in;
 var options_in;
 return operator()(mode_in, options_in);
}

var operator() (in mode) {
 var options_in;
 return operator()(mode, options_in);
}

};
efb_shadowmfs shadowmfs{mv};
//#endif
