/*
Copyright (c) 2009 steve.bush@neosys.com

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#ifndef _MSC_VER
#	define EXODUS_POSIX_SOURCE
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#	define _OSSLASH "/"
#pragma clang diagnostic pop
#endif

// For debugging
#define TRACING 0

#if EXO_MODULE
	import std;
#else
#	include <stdio.h>
#	include <cstdlib>
#	include <iostream>
#	include <string>
#	include <unistd.h> // for getpid
//#	include <signal.h>
#	include <memory> // for make_unique
#endif

#include <termios.h>
#include <execinfo.h> // for backtrace
#include <csignal>

#if TRACING
#	include <boost/stacktrace.hpp>
#endif
//#include <backward.hpp>

#include <exodus/var.h>
#include <exodus/exoimpl.h>
#include <exodus/range.h>
#include "exodebug.h"

namespace exo {

using let = const var;

static void addbacktraceline(in frameno, in sourcefilename, in lineno, io returnlines) {

	//#if TRACING
	//	sourcefilename.errputl("SOURCEFILENAME=");
	//	lineno.errputl("LINENO=");
	//#endif

	bool raw = true;

	if ((not lineno || not lineno.isnum()) and not raw)
		return;

	// Get the source file text
	var filetext;
	if (not filetext.osread(sourcefilename)) {
		if (not raw)
			return;
		filetext = "";
	}

	// Change DOS/WIN and MAC line ends to lf only
	filetext.replacer("\x0D\x0A", "\x0A");
	filetext.converter("\x0D", "\x0A");

	// Extract the source line
	let line = lineno.isnum() ? filetext.field("\x0A", lineno).trimfirst(" \t") : "";
	if ((not line or line.match("^\\s*}")) and not raw)
		return;

	// Suppress confusing and unhelpful exodus macros like programinit/exit, libraryinit/exit, classinit/exit
	if (/* not raw and */ line.match("^(program|library|class)(init|exit)\\("))
		return;

	// Skip "return nn"
	if (line.match("^\\s*return\\s*\\d*") and not raw)
		return;

#if TRACING
	line.errputl();
#endif

	// Example output line:
	// "8: p2.cpp:15: printl(v2);"
	let linetext = (frameno) ^ ": " ^ sourcefilename.field(_OSSLASH, -1) ^ ":" ^ lineno ^ ":\t" ^ line;
	//var linetext = std::format("{:0}: {:1}:{:2}: {:3}" , frameno, sourcefilename.field2(_OSSLASH, -1), lineno, line);

	returnlines ^= linetext ^ FM;

	return;
}

var summarise_gdb_bt(in osfilename) {

	var result = "";
	var currthreadno = "";
	var currthreadtitle = "";
	var txt;
	if (not txt.osread(osfilename))
		return "";
	txt.converter(NL, FM);
	for (var line : txt) {
//			TRACE(line);
		if (line.starts("Thread ")) {
			let threadno = line.field(" ", 2);
			if (threadno > 1 or currthreadno)
				currthreadtitle = line.field(" ", 1, 2);
			currthreadno = threadno;
		}
		if (line.starts("#")) {

			// e.g.
			// #12 _ExoProgram::main3 (this=this@entry=0x7ffc342fdb00, call_id=..., N=..., mode=...) at /root/exodus/exodus/t1.cpp:75 {
			//
			//#10 0x00007fa494b44a9b in _ExoProgram::main (this=<optimized out>) at exo/waiting.cpp:56
			// TODO also find sub_ExoProgram
			if (not line.trim().field(" ", 2).contains("_ExoProgram") and not line.contains("in _ExoProgram"))
				continue;

			var srcfileline = line.field(" ", -1);
			var srcfileline2 = srcfileline.field("/", -2, 2);
//				if (srcfileline2.starts("exodus/"))
//					continue;
//				TRACE(srcfileline)
			if (srcfileline.field("/", -1).count(":") == 1) {

				// Try to resolve relative path by lookup in ~/inc
				if (not srcfileline.starts("/")) {
					//exo/waiting.cpp:56
					var incfilename = "~/inc/" ^ srcfileline.field("/", -1).field(":", 1).field(".", 1) ^ ".h";
					var incfile;
					if (incfile.osread(incfilename) or incfile.osread(incfilename.paste(-1, 1, "H"))) {
						// //Generated by exodus "compile /root/exodus/service/src/exo/waiting.cpp"
						var target = incfile.field("\"", 2).field(" ", 2).trim();
						if (not target.starts("/"))
							target = incfile.match(R"___([^/]/[a-zA-Z0-9_./]+)___").f(1, 1).cut(1);
						if (target.starts("/"))
							srcfileline = target ^ ":" ^ srcfileline.field(":", 2);
					}
				}

				var src;
				if (not src.osread(srcfileline.field(":",1)))
					continue;
				src = src.field(NL, srcfileline.field(":",2));
				line = line.field(" ", 1) ^ " " ^ srcfileline2 ^ "\t" ^ src.trimboth(" \t");
				if (currthreadtitle) {
					// Thread 1 is usually last.
					// and we dont output it unless other threads already output.
					currthreadtitle.logputl();
					currthreadtitle = "";
				}
				result.appender(line, _NL);
			}
		}
	}
	result.popper();
	return result;
}

////////////////////////////////////////////////////////////////////
//// Reserve space for snapshot of stack taken on every mv exception
////////////////////////////////////////////////////////////////////
//// in case the exception is caught then it is wasted time
//namespace {
//	#define BACKTRACE_MAXADDRESSES 100
//	thread_local void* thread_stack_addresses[BACKTRACE_MAXADDRESSES];
//	thread_local std::size_t thread_stack_size = 0;
//}

//// Capture the current stack addresses for later decoding
//void exo_savestack(void* stack_addresses[BACKTRACE_MAXADDRESSES], std::size_t* stack_size) {
//	*stack_size = ::backtrace(stack_addresses, BACKTRACE_MAXADDRESSES);
//#if TRACING
//	std::cout << boost::stacktrace::stacktrace();
//#endif
//}

// Capture the current stack addresses for later decoding.
// false indicates that gdb is available but already attached and caller can throw to get into gdb.
// We always get the basic stack and gdb is to get accurate backtrace in backtrace.$pid.log
auto exo_savestack(void* stack_addresses[BACKTRACE_MAXADDRESSES], std::size_t* stack_size) -> bool{

	// Always get the basic stack because it is quick
	// but is it not very accurate inside threads and fibers
	*stack_size = ::backtrace(stack_addresses, BACKTRACE_MAXADDRESSES);

	// EXO_DEBUG=0 to suppress using gdb for backtracing.
	// Speeds up testing various VarError conditions which use try/catch and dont need backtracing.
	var exo_debug;
	if (exo_debug.osgetenv("EXO_DEBUG") and not exo_debug)
		return true;

#if TRACING
	std::cerr << "Attaching GDB to PID: " << getpid() << "\n";
#endif
	std::string pid = std::to_string(getpid());

//	std::string gdb_cmd = "gdb -batch -p " + pid + " -ex 'thread apply all bt full' -ex 'detach' -ex 'quit' > backtrace." + pid + ".log 2>/dev/null";

	if (not "which gdb")
		return true;

	let logfilename = "backtrace." ^ var::ospid() ^ ".log";
	std::cerr << "----- gdb " << logfilename << " -----" << std::endl;

	// Get all thread info because there is no gdb command to switch to thread (LWP) by LWP id.
	var gdb_cmds = " -ex 'thread apply all bt' -ex 'detach' -ex 'quit'";
	var gdb_cmd = "gdb -batch -p " ^ pid ^ gdb_cmds ^ " > backtrace." ^ pid ^ ".log 2>/dev/null < /dev/null";

	if (system(gdb_cmd.c_str()) != 0) {
		// gdb not installed. Rely on ::backtrace above which isnt very accurate in threads or fibers.
		return true;
	}
//	if (not gdb_cmd.osshell()) {
//		var::lasterror().logputl();
//		return true;
//	}

	var txt;
	if (not txt.osread(logfilename)) {
		// gdb not installed. Rely on ::backtrace above which isnt very accurate in threads or fibers.
//		std::cerr << "Could not attach gdb" << std::endl;
		return true;
	}

	// If running under gdb or gdb already attached then we cannot attach again.
	if (not txt.contains("#0")) {
		std::clog << "gdb is already attached to pid " << var::ospid() << ". Search backtrace starting ExoProgram." << std::endl;
		// Could not attach to process.  If your uid matches the uid of the target
		// process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
		// again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
		return false;
	}

//	std::cerr << "----- gdb " << logfilename << " -----" << std::endl;

	// EXO_DEBUG=1 signifies desire to break into gdb.
	// instead being caught by program or perform/execute/run exception handlers
	// EXO_DEBUG=1 used to signify running under gdb
	// but now we can detect that automatically by an inability to attach dynamically.
	// TODO Move to VarError handler?
	if (not exo_debug.empty()) {
		// EXO_DEBUG=0 to suppress using it for backtracing. Speeds up testing various VarError conditions.
		if (exo_debug) {

			// Display filtered backtrace
			summarise_gdb_bt(logfilename).logputl();

			std::cerr << var("-").str(logfilename.len() + 16) << std::endl;

			// Patch .gdbinit to suppress long list of system file symbol loading
			var gdbinit;
			bool gdbinit_update = false;
			if (gdbinit.osread("~/.gdbinit")) {
				if (not gdbinit.contains("symbol-loading")) {
					gdbinit ^=
						"\n"
						"# Suppress long list when auto-attaching to gdb in new version of Exodus.\n"
						"set print symbol-loading off\n"
					;
					gdbinit_update = true;
				}
				if (not gdbinit.contains("debuginfod")) {
					gdbinit ^=
						"\n"
						"# Suppress long list when auto-attaching to gdb in new version of Exodus.\n"
						"set debuginfod enabled off\n"
					;
					gdbinit_update = true;
				}
				if (gdbinit_update and gdbinit.oswrite("~/.gdbinit"))
					var("~/.gdbinit updated.").logputl();
			}

//			// Search backtrace for lines starting _ExoProgram
//			var("Search backtrace for lines starting _ExoProgram.").logputl();
//			let cmd1 = "gdb -q -p " ^ var::ospid() ^ " -ex 'bt' -ex 'detach' -ex 'quit' 2> /dev/null | grep -P '^#[0-9]+\\s+_ExoProgram'";
//			system(cmd1);

			// Attach gdb interactively
			let cmd = "gdb -q -p " ^ var::ospid();
			cmd.logputl();
			if (system(cmd) == 0) {
				// gdb use completed.
			} else {
				// gdb not installed or already attached?
			}

		} else {
			// No gdb but use ::backtrace stack addresses captured above
			return true;
		}
	}

//	else
//		std::cerr << "Backtrace saved to backtrace.log\n";

//#if TRACING
//	std::cout << boost::stacktrace::stacktrace();
//#endif
	return true;
}

//}

////////////////////////////////////////////////////////////////////
// Given stack addresses, get the source file, line no and line text
////////////////////////////////////////////////////////////////////
// http://www.delorie.com/gnu/docs/glibc/libc_665.html
auto exo_backtrace(void* stack_addresses[BACKTRACE_MAXADDRESSES], std::size_t stack_size, std::size_t limit) -> std::string {

	// Utilise gdb backtrace.$pid.log if available
	var returnlines = summarise_gdb_bt("backtrace." ^ var::ospid() ^ ".log");
	if (returnlines)
		return returnlines;

	std::size_t nlines = 0;
	var mangled_addresses = "";

	let internaladdresses = "";

//Backtrace 0: 0x7624d8bac192 "/root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07(_ZN3exo13exo_savestackEPPvPm+0x12) [0x7624d8bac192]"
//objdump --start-address=0000 --stop-address=0x12 --source --line-numbers /root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07
//
//Backtrace 1: 0x7624d8b9a8eb "/root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07(_ZN3exo8VarErrorC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x9b) [0x7624d8b9a8eb]"
//objdump --start-address=0000 --stop-address=0x9b --source --line-numbers /root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07
//
//Backtrace 2: 0x7624d8b9b23a "/root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07(_ZN3exo13VarUnassignedC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3a) [0x7624d8b9b23a]"
//objdump --start-address=0000 --stop-address=0x3a --source --line-numbers /root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07
//
//Backtrace 3: 0x566f66d595cb "/root/exodus/build/cli/src/gendoc(+0x135cb) [0x566f66d595cb]"
//objdump --start-address=0x13000 --stop-address=0x135cb --source --line-numbers /root/exodus/build/cli/src/gendoc
//
//Backtrace 4: 0x566f66d594e6 "/root/exodus/build/cli/src/gendoc(+0x134e6) [0x566f66d594e6]"
//objdump --start-address=0x13000 --stop-address=0x134e6 --source --line-numbers /root/exodus/build/cli/src/gendoc
//
//Backtrace 5: 0x566f66d53c27 "/root/exodus/build/cli/src/gendoc(+0xdc27) [0x566f66d53c27]"
//objdump --start-address=0xd000 --stop-address=0xdc27 --source --line-numbers /root/exodus/build/cli/src/gendoc
//if (man) {
//
//Backtrace 6: 0x566f66d4baa1 "/root/exodus/build/cli/src/gendoc(+0x5aa1) [0x566f66d4baa1]"
//objdump --start-address=0x5000 --stop-address=0x5aa1 --source --line-numbers /root/exodus/build/cli/src/gendoc
//programexit()
//
//Backtrace 7: 0x7624d822a1ca "/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca) [0x7624d822a1ca]"
//Backtrace 8: 0x7624d822a28b "/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b) [0x7624d822a28b]"
//Backtrace 9: 0x566f66d4b8b5 "/root/exodus/build/cli/src/gendoc(+0x58b5) [0x566f66d4b8b5]"
//objdump --start-address=0x5000 --stop-address=0x58b5 --source --line-numbers /root/exodus/build/cli/src/gendoc

	// TODO autodetect if addr2line or dwalfdump/dSYM is available

	//warning: conversion from ‘std::size_t’ {aka ‘long unsigned int’} to ‘int’ may change value [-Wconversion]
	//char** strings = backtrace_symbols(stack_addresses, static_cast<int>(stack_size));
	auto strings = std::unique_ptr<char*[], void(*)(void*)>{backtrace_symbols(stack_addresses, static_cast<int>(stack_size)), ::free};

	for (std::size_t frameno = 0; frameno < stack_size; frameno++) {

		// To find source lines using objdump we need to know the file name and absolute address in the file

		var objfilename = var(strings[frameno]).field("(", 1).field(" ", 1).field("[", 1);
		var objaddress = var(strings[frameno]).field("[", 2).field("]", 1);

		// Skip libc
//#if TRACING < 2
		if (objfilename.contains("libc.so"))
			continue;
//#endif

#if TRACING
		fprintf(stderr, "Backtrace %d: %p \"%s\"\n", int(frameno), stack_addresses[frameno], strings[frameno]);
		// Backtrace 0: 0x7f9d247cf9fd
		// "/usr/local/lib/libexodus.so.19.01(_ZN6exodus9backtraceEv+0x62) [0x7f9d247cf9fd]"
		// Backtrace 5: 0x7f638280e3f6 "/root/lib/libl1.so(+0xa3f6) [0x7f638280e3f6]"
#endif

		// Use gdb by preference because it finds source file, line numbers AND source line all in one
		static bool gdb = var("which gdb > /dev/null").osshell();
		if (gdb) {
			var objaddress = var(strings[frameno]).field("(", 2).field(")", 1);
			//gdb --batch -ex "file /root/exodus/build/exodus/libexodus.so.24.07" -ex "list *(_ZN3exo13exo_savestackEPPvPm+0x12)"
			//0x124992 is in exo::exo_savestack(void**, unsigned long*) (/root/exodus/exodus/exodebug.cpp:120).
			//115	 //	  thread_local std::size_t thread_stack_size = 0;
			//116	 //}
			//117
			//118	 // Capture the current stack addresses for later decoding
			//119	 void exo_savestack(void* stack_addresses[BACKTRACE_MAXADDRESSES], std::size_t* stack_size) {
			//120			 *stack_size = ::backtrace(stack_addresses, BACKTRACE_MAXADDRESSES);
			//121	 #if TRACING
			//122			 std::cout << boost::stacktrace::stacktrace();
			//123	 #endif
			//124	 }
			//07:52:45 root@de1:~/exodus/exodus#
			var stdout;
			var stderr;
			var exit_status;
			let cmd = "gdb --batch -ex \"file " ^ objfilename ^ "\" -ex \"list *(" ^ objaddress ^ ")\"";
//				TRACE(cmd)
			if (var::osprocess(cmd, "", stdout, stderr, exit_status)) {
				let source_file_line = stdout.field(_NL, 1).field("(", -1).field(")", 1);
				let lineno = source_file_line.field(":", 2);
				var col2;
				let sourceline = stdout.substr(stdout.index(_NL ^ lineno ^ "\t") + 1, _NL, col2).cut(lineno.len()).trimfirst(" \t");
//				addbacktraceline(frameno, source_file_line, sourceline, returnlines);
				returnlines ^= var(frameno) ^ ": " ^ source_file_line ^ ":\t" ^ sourceline ^ FM;
				continue;
			}
		}

		// Handle high addresses that are random loaded .so and therefore useless.
		if (objaddress.len() > 9) {
			objaddress = var(strings[frameno]).field("(", 2).field(")", 1);
			if (objaddress.starts("+")) {
				// "/root/lib/liblistsched.so(+0x8067) [0x7fe49722a067]"
				objaddress.cutter(1);
			}
			else {
				// Handle FUNCNAME+RELATIVE address by not adding source line for now.
				// TODO
				// Anything before the + means a relative address and we havent bothered to code for it.
				// /usr/local/lib/libexodus.so.24.07(_ZN3exo10ExoProgram7performERKNS_3varE+0x5d0) [0x7fe49b202710]
				if (not objfilename.contains("libexodus.so")) {
					addbacktraceline(frameno, objfilename.field("/", -1), "", returnlines);
					continue;
				}
			}
		}

		// objdump --stop-address=0xa3f6 -l --disassemble ~/lib/libl1.so |grep cpp|tail -n1

		// Skip libexodus source code
		//if (not exo_debug and objfilename.contains("libexodus.so"))
		//if (objfilename.contains("libexodus.so"))
		//	continue;

//#if TRACING
//		fprintf(stderr, " %s addr:%s\n", objfilename.c_str(), objaddress.c_str());
////		objfilename.errput("objfilename=");
////		objaddress.errputl(" objaddress=");
//#endif

		// if (objfilename == objfilename.convert("/\\:",""))
//TRACE(objfilename)	  // "/root/exodus/build/exodus/libexodus/exodus/libexodus.so.24.07"
//TRACE(objfilename)	  // "/root/exodus/build/cli/src/gendoc"

		if (not objfilename.osfile()) {
			// loadable program
			var which_out;
			if (not which_out.osshellread("which " ^ objfilename.field(_OSSLASH, -1))) {
				//null
			}
			which_out = which_out.field("\n", 1).field("\r", 1);
			if (which_out)
				objfilename = which_out;
			else
				// things like what?
				continue;
		}

		// Skip if hex address is invalid
		if (not objaddress.starts("0") || objaddress.at(2) != "x") {
			mangled_addresses.appender(objaddress, FM_);
			let linetext = var(frameno) ^ ": " ^ objfilename.field(_OSSLASH, -1) ^ ":" ^ objaddress;
			returnlines ^= linetext ^ FM;
			continue;
		}

		// Start at the beginning of a hex block
		let startaddress = objaddress.paste(-3, 3, "000");
//		let stopaddress = objaddress;
//		let startaddress = objaddress;

//		let startaddress = objaddress;
		// Stop 1 after after the start address
		let stopaddress = "0x" ^ (objaddress.cut(2).iconv("MX") + 1).oconv("MX");

		////////////////////////
		//objdump_out = objdump_out.osshellread();
		var objdump_out;
		let cmd =
			"objdump"
			" --start-address=" ^ startaddress ^
			" --stop-address=" ^ stopaddress ^
//			" --disassemble -l " ^ objfilename ^
			" --source"
			" --line-numbers " ^
			objfilename;

#if TRACING
		cmd.errputl();
#endif
		if (not objdump_out.osshellread(cmd))
			continue;
		////////////////////////

		objdump_out.converter("\r\n", _FM _FM);

		// Find the last line containing .cpp
		/// root/exodus/exodus/libexodus/exodus/l1.cpp:7 (discriminator 3)
		const var nn2 = objdump_out.fcount(FM);
		var line = "";
		let linesource = "";
		//for (var frameno2 = 1; frameno2 < nn2; ++frameno2) {
		for (var frameno2 : reverse_range(1, nn2)) {
			if (objdump_out.f(frameno2).contains(".cpp:")) {
//				let nextline = objdump_out.f(frameno2);
//				// Skip disassembly lines
//				if (not nextline.match("	[0-9a-f]: ")) {
//					// Skip lines like "return 1;" since they seem to be spurious
//					if (nextline.match("^\\s*return\\s*\\d+;"))
//						break;
					line = objdump_out.f(frameno2);
//					linesource = nextline;
//#if TRACING
//					TRACE(line)
//					TRACE(linesource)
//#endif
					break;
//				}
			}
		}

//#if TRACING
//		if (line)
//			line.errputl("line=");
//#endif

		// Skip library internals
		if (objfilename.contains("libexodus.so"))
			continue;

		// append the source line text and number to the output
		if (line) {
			let sourcefilename = line.field(":", 1);
			let lineno = line.field(":", 2).field(" ", 1);
			addbacktraceline(frameno, sourcefilename, lineno, returnlines);
			//7: p1.cpp:13: return 1;
			//returnlines ^= var(frameno + 1) ^ ": " ^ sourcefilename ^ ":" ^ lineno ^ ": " ^ linesource ^ FM;
			//returnlines ^= var(frameno + 1) ^ ": " ^ line.field2(_OSSLASH, -1) ^ " " ^ linesource ^ FM;
		} else if (not objfilename.contains("libexodus.so")) {
			addbacktraceline(frameno, objfilename.field("/", -1), "", returnlines);
		}

#if TRACING
		var("").errputl();
#endif
		// Quit if reached limit of desired backtrace
		if (limit && nlines++ >= limit)
			break;

	}

	if (mangled_addresses) {
		var stdout;
		var stderr;
		var exit_status;
		if (var::osprocess("c++filt", mangled_addresses.convert(_FM, _NL), stdout, stderr, exit_status)) {
			var ii = 0;
			stdout.converter(_NL, _FM);
			mangled_addresses.trimmerlast(_FM);
			for (var mangled_address : mangled_addresses)
				returnlines.replacer(mangled_address, stdout.f(++ii));
		}
	}

	// Handled automatically by unique_ptr
	//::free(strings);

	returnlines.popper();
	return returnlines;

}

/* Possible plan to extend exodus signal handling
	SIGHUP
	Reload config. Same as issuing the command RELOAD on the console.
	SIGTERM
	Super safe shutdown. Wait for all existing clients to disconnect, but don’t accept new connections. This is the same as issuing SHUTDOWN WAIT_FOR_CLIENTS on the console. If this signal is received while there is already a shutdown in progress, then an “immediate shutdown” is triggered instead of a “super safe shutdown”. In PgBouncer versions earlier than 1.23.0, this signal would cause an “immediate shutdown”.
	SIGINT
	Safe shutdown. Same as issuing SHUTDOWN WAIT_FOR_SERVERS on the console. If this signal is received while there is already a shutdown in progress, then an “immediate shutdown” is triggered instead of a “safe shutdown”.
	SIGQUIT
	Immediate shutdown. Same as issuing SHUTDOWN on the console.
	SIGUSR1
	Same as issuing PAUSE on the console.
	SIGUSR2
	Same as issuing RESUME on the console.
*/
//service managers like systemd will send a polite SIGTERM signal
//and wait for say 90 seconds before sending a kill signal
static void SIGTERM_handler(int) {
	fprintf(stderr, "=== SIGTERM_handler: Set TERMINATE_req = true ===\n");
	TERMINATE_req = true;
}

//restart
static void SIGHUP_handler(int) {
	fprintf(stderr, "=== SIGHUP_handler: Set RELOAD_req = true ===\n");
	RELOAD_req = true;
}

PUBLIC void breakoff() {
	// ignore this signal (Typically Ctrl+C) until breakon
	signal(SIGINT, SIG_IGN);
}

PUBLIC void breakon();

//signals are received by one thread at random
//void SIGINT_handler(int sig) {
static void SIGINT_handler(int sig [[maybe_unused]]) {

	// Save stdin terminal attributes
	// Probably not available if running as a service
	struct termios oldtio, curtio;
	bool has_oldtio = false;
	if (tcgetattr(STDIN_FILENO, &oldtio) < 0) {
		//EBADF - The filedes argument is not a valid file descriptor.
		//ENOTTY - The filedes is not associated with a terminal.
		//	  var("no std input").outputl();
		//	  return false;
	} else {
		has_oldtio = true;
//		nfds = 2;

		//Make sure we exit cleanly
		// memset(&sa, 0, sizeof(struct sigaction));
		// sa.sa_handler = sighandler;
		// sigaction(SIGINT, &sa, nullptr);
		// sigaction(SIGQUIT, &sa, nullptr);
		// sigaction(SIGTERM, &sa, nullptr);

		//This is needed to be able to tcsetattr() after a hangup (Ctrl-C)
		//see tcsetattr() on POSIX

		// memset(&sa, 0, sizeof(struct sigaction));
		// sa.sa_handler = SIG_IGN;
		// sigaction(SIGTTOU, &sa, nullptr);

		// Set stdin mode
		// a) non-canonical (i.e. characterwise not linewise input)
		// b) no-echo
		// https://man7.org/linux/man-pages/man3/termios.3.html
		//
		tcgetattr(STDIN_FILENO, &curtio);
		curtio.c_lflag |= (ICANON | ECHO);
		tcsetattr(STDIN_FILENO, TCSANOW, &curtio);
	}

	// Ignore more of this signal - restore on exit
//	breakoff();
	// Faster/safer?
	signal(sig, SIG_IGN);

	// Hide input characters
	//var().echo(true);

	// duplicated in init and B
	// backtrace().convert(FM,"\n").errputl();

	// Capture the current stack and trigger debugger
//	VarError err("backtrace()");

	// interact on a new line
//	fprintf(stderr, "SIGINT_handler\n");

	// Break straight into debugger via stack capture
	var exo_debug;
	if (exo_debug.osgetenv("EXO_DEBUG") and exo_debug) {
            // Attach gdb interactively
            let cmd = "gdb -q -p " ^ var::ospid();
            cmd.logputl();
            if (system(cmd) == 0) {
                // gdb use completed.
            } else {
                // gdb not installed or already attached?
            }
	}

	while (not exo_debug) {

//		fprintf(stderr, "SIGINT_handler loop\n");
		var cmd = "A";

		if (var().isterminal()) {
			fprintf(stderr, "Interrupted. (C)ontinue (Q)uit (A)bort (B)acktrace (D)ebug ? ");
			fflush(stderr);
			if (!cmd.inputn(1))
				continue;
		}

		// only look at first character in uppercase
		let cmd1 = var(cmd.first()).ucase();

		if (cmd1 == "C") {

			fprintf(stderr, "ontinuing ...\n");
			fflush(stderr);

			// Continue
			break;

		} else if (cmd1 == "Q") {

			// Quit ... unfortunately to the caller at the moment.
			// TODO flag to caller(s) to exit

			// var().abort("Aborted. User interrupt");
			fprintf(stderr, "uitting ...\n");

			// Quit
			exit(1);

		} else if (cmd1 == "B") {

			fprintf(stderr, "acktracing ...\n");
			fflush(stderr);			// duplicated in init and B

			// Backtrace
			VarError err("SIGINT_handler");
			var(err.stack()).convert(FM, "\n").errputl();

		} else if (cmd1 == "D") {

			fprintf(stderr, "ebugging ... ");
			fflush(stderr);			// duplicated in init and B

			breakon();
			var().echo(1);
			// Debugging
			// duplicated in init and B
			let pid = getpid();
			let cmd = "gdb -p " ^ pid;
			cmd.logputl(" ");
			if (not cmd.osshell())
				var().lasterror().logputl();

		} else if (cmd1 == "A") {

			fprintf(stderr, "borting ...\n");
			fflush(stderr);			// duplicated in init and B

			// Abort using SIGABT
			// fprintf(stderr,"To continue from here in GDB: \"signal 0\"\n");
			raise(SIGABRT);
			// breakpoint();

		} else {

			// Invalid option - try again.
			fprintf(stderr, "\n");
		}

	}

	// restore terminal attributes (probably linewise input and echo)
//	if (nfds == 2) {
	if (has_oldtio)
		tcsetattr(STDIN_FILENO, TCSANOW, &oldtio);
//	}
	// Show input characters
	//var().echo(true);

	// Stop ignoring this signal
//	breakon();
	// faster/safer?
	fprintf(stderr, "restablish SIGINT_handler\n");
	signal(SIGINT, SIGINT_handler);

}

//called in exodus_main to initialise signals
PUBLIC void breakon()  {

	signal(SIGINT, SIGINT_handler);	   // Ctrl+C from termio

	signal(SIGTERM, SIGTERM_handler);  // a polite request to TERMINATE
									   // probably followed by SIGABORT after some delay

	signal(SIGHUP, SIGHUP_handler);	   // a request to reload

	//turn off text input and output signals to prevent breaking out into gdb debugger
	//http://curiousthing.org/sigttin-sigttou-deep-dive-linux
	signal(SIGTTIN, SIG_IGN);
	signal(SIGTTOU, SIG_IGN);
}

// Get a stack list on demand
ND PUBLIC auto backtrace() -> std::string {
	VarError e("backtrace()");
	return e.stack();
}

PUBLIC void debug(SV var1) {

	if (!var1.empty())
		std::clog << "debug(" << var1 << ")" << std::endl;
	std::cout << std::flush;

	//use gdb "n" command(s) to single step
	//use gdb "c" command(s) to resume

#if __has_include(<signal.h>)
	::raise(SIGTRAP);

#elif 1
	__asm__("int3");
	//__asm__("int3");
	//__asm__("int3");

#elif defined(_MSC_VER)
	// this will terminate the program rather than invoke the debugger but is catchable
	//UNLIKELY throw VarDebug(var1);

// another way to break into the debugger by causing a seg fault
#elif 0
	*(int*)0 = 0;
#endif

	return;
}

}  // namespace exo
