//generated by exodus "compile ../job/addjobacc"
//#ifndef EXODUSDLFUNC_ADDJOBACC_H
#define EXODUSDLFUNC_ADDJOBACC_H

//a member variable/object to cache a pointer/object for the shared library function
//ExodusFunctorBase efb_addjobacc;
class efb_addjobacc : private ExodusFunctorBase
{
public:

efb_addjobacc(MvEnvironment& mv) : ExodusFunctorBase("addjobacc", "exodusprogrambasecreatedelete_", mv) {}

efb_addjobacc& operator=(const var& newlibraryname) {
        closelib();
        libraryname_=newlibraryname.toString();
}

//a member function with the right arguments, returning a var or void
var operator() (in addaccmode, in jobno, io msg)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 //if (efb_getlang.pmemberfunction_==NULL)
 // efb_getlang.init("getlang","exodusprogrambasecreatedelete_",mv);
 if (this->pmemberfunction_==NULL)
  this->init();

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 //return CALLMEMBERFUNCTION(*(efb_addjobacc.pobject_),
 //((pExodusProgramBaseMemberFunction) (efb_addjobacc.pmemberfunction_)))
 // (mode);
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (addaccmode,jobno,msg);

}

};
efb_addjobacc addjobacc{mv};
//#endif
