//generated by exodus "compile createjob"
//#ifndef EXODUSDLFUNC_CREATEJOB_H
#define EXODUSDLFUNC_CREATEJOB_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_createjob;

//a member function with the right arguments, returning a var or void
var createjob(io job, in jobno)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_createjob.pmemberfunction_==NULL)
  efb_createjob.init("createjob","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(io,in);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_createjob.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_createjob.pmemberfunction_)))
  (job,jobno);

}
//#endif
