//generated by exodus "compile validjob"
//#ifndef EXODUSDLFUNC_VALIDJOB_H
#define EXODUSDLFUNC_VALIDJOB_H

//a member variable/object to cache a pointer/object for the shared library function
ExodusFunctorBase efb_validjob;

//a member function with the right arguments, returning a var or void
var validjob(in mode0, in jobno, io job, io msg)
{

 //first time link to the shared lib and create/cache an object from it
 //passing current standard variables in mv
 if (efb_validjob.pmemberfunction_==NULL)
  efb_validjob.init("validjob","exodusprogrambasecreatedelete_",mv);

 //define a function type (pExodusProgramBaseMemberFunction)
 //that can call the shared library object member function
 //with the right arguments and returning a var or void
 typedef var (ExodusProgramBase::*pExodusProgramBaseMemberFunction)(in,in,io,io);

 //call the shared library object main function with the right args,
 // returning a var or void
 return CALLMEMBERFUNCTION(*(efb_validjob.pobject_),
 ((pExodusProgramBaseMemberFunction) (efb_validjob.pmemberfunction_)))
  (mode0,jobno,job,msg);

}
//#endif
