.TH dim.h
 Code examples - dim.h

.SH 22. ARRAY CONSTRUCTION 
.SH

.SS
dim d1;
.nf
 
.fi
Create an undimensioned array.

.SS
dim d1 = d2;
.nf
 
.fi
Copy an array.

.SS
dim d1 = dim();
.nf
 
.fi
Save an array created elsewhere.

.SS
dim.swap(dim& rhs) noexcept
.nf
 
.fi
Swap member (handles both base and ncols_)

.SS
dim d1(nrows, ncols = 1);
.nf
 
.fi
Create an array of vars with a fixed number of columns and rows. All vars are unassigned.

.SS
d1.redim(nrows, ncols = 1)
.nf
 
.fi
Resize an array to a different number of rows and columns.

Existing data will be retained as far as possible. Any additional elements are unassigned.

Resizing rows to 0 clears all data. Resizing cols to 0 clears all data and changes its status to "undimensioned".

.SS
dim d1 = {"a", "b", "c" ...};
.nf
 
.fi
Create an array from a list. All elements must be the same type, string, double or int.

.SH 23. ARRAY ACCESS
.SH

.SS
var v1 = d1.rows();
.nf
 
.fi
Get the number of rows in the dimensioned array

\fBReturns:\fR A count

.SS
var v1 = d1.cols();
.nf
 
.fi
Get the number of columns in the dimensioned array

\fBReturns:\fR A count

.SS
var v1 = d1.join(delimiter = FM);
.nf
 
.fi
Joins all elements into a single delimited string

\fBReturns:\fR A string var

.SH 24. ARRAY MUTATION
.SH

.SS
d1.splitter(str1, delimiter = FM)
.nf
 
.fi
Creates or updates the array from a given string.

If the dim array has not been dimensioned (nrows and ncols are 0), it will be dimensioned with the number of elements that the string has fields.

If the dim array has already been dimensioned, and has more elements than there are fields in the string, the excess array elements are initialised to "". If the record has more fields than there are elements in the array, the excess fields are all left unsplit in the final element of the array.

Predimensioning arrays allows efficient reuse of arrays in loops.

In either case, all elements of the array are updated.

\fBExample:\fR
.RS
.nf
 dim d1;
 d1.splitter("f1^f2^f3"_var); // d1.rows() -> 3
 //
 dim d2(10);
 d2.splitter("f1^f2^f3"_var); // d2.rows() -> 10
.fi
.RE


.SS
d1.sorter(reverse = false)
.nf
 
.fi
Sort the elements of the array in place.

\fBreverseorder:\fR Defaults to false. If true, then the order is reversed.

.SS
d1.reverser()
.nf
 
.fi
Reverse the elements of the array in place.

.SS
d1.shuffler()
.nf
 
.fi
Randomly shuffle the order of the elements of the array in place.

.SH 25. ARRAY CONVERSION
.SH

.SS
d1.sort(reverseorder = false)
.nf
 
.fi
Same as sorter() but returns a new array leaving the original untouched.

.SS
d1.reverse()
.nf
 
.fi
Same as reverser() but returns a new array leaving the original untouched.

.SS
d1.shuffle()
.nf
 
.fi
Same as shuffler() but returns a new array leaving the original untouched.

.SH 26. ARRAY READ/WRITE
.SH

.SS
d1.write(dbfile, key)
.nf
 
.fi
Writes a db file record created from an array.

Each element in the array becomes a separate field in the db record. Any redundant trailing FMs are suppressed.

\fBExample:\fR
.RS
.nf
 dim d1 = "Client GD^G^20855^30000^1001.00^20855.76539"_var.split();
 let file = "xo_clients", key = "GD001";
 if (not deleterecord("xo_clients", "GD001")) {}; // Cleanup first
 d1.write(file, key);
 // or
 write(d1 on file, key);
.fi
.RE


.SS
if (d1.read(dbfile, key)) ...
.nf
 
.fi
Read a db file record into an array.

Each field in the database record becomes a single element in the array.

\fBReturns:\fR True if the record exists or false if not,

If the array is predimensioned then any excess array elements are initialised to "" and any excess record fields are left unsplit in the final array element. See dim splitter for more info.

If the array is not predimensioned (rows and cols = 0) then it will be dimensioned to have exactly the same number of rows as there are fields in the record being read.

\fBExample:\fR
.RS
.nf
 dim d1(10);
 let file = "xo_clients", key = "GD001";
 if (not d1.read(file, key)) ... // d1.join() -> "Client GD^G^20855^30000^1001.00^20855.76539"_var
 // or
 if (not read(d1 from file, key)) ...
.fi
.RE


.SS
if (d1.oswrite(osfilename, codepage = "")) ...
.nf
 
.fi
Creates an entire os text file from an array

Each element of the array becomes one line in the os file delimited by \\n

Any existing os file is overwritten and replaced.

\fBcodepage:\fR Optional: Data is converted from UTF8 to the required codepage/encoding before output. If the conversion cannot be performed then return false.

\fBReturns:\fR True if successful or false if not.

\fBExample:\fR
.RS
.nf
 dim d1 = "aaa=1\\nbbb=2\\nccc=3\\n"_var.split("\\n");
 if (not osremove("xo_conf.txt")) {}; // Cleanup first
 let osfilename = "xo_conf.txt";
 if (not d1.oswrite(osfilename)) ...
 // or
 if (not oswrite(d1 on osfilename)) ...
.fi
.RE


.SS
if (d1.osread(osfilename, codepage = "")) ...
.nf
 
.fi
Read an entire os text file into an array.

Each line in the os file, delimited by \\n or \\r\\n, becomes a separate element in the array.

\fBcodepage:\fR Optional. Data will be converted from the specified codepage/encoding to UTF8 after being read. If the conversion cannot be performed then return false.

\fBReturns:\fR True if successful or false if not.

If the first \\n in the file is \\r\\n then the whole file will be split using \\r\\n as delimiter.

\fBExample:\fR
.RS
.nf
 dim d1;
 let osfilename = "xo_conf.txt";
 if (not d1.osread(osfilename)) ... // d1.join("\\n") -> "aaa=1\\nbbb=2\\nccc=3\\n"_var0
 // or
 if (not osread(d1 from osfilename)) ...
.fi
.RE



