.TH dim.h
 Code examples - dim.h

.SH 22. DIM CONSTRUCTION 
.SH

.SS
if (dim.redim(nrows, ncols = 1)) ...
.nf
 
.fi


.SS
dim.at(rowno, colno)
.nf
 
.fi
Transition alternative for () and [] syntax to be used in libexodus, cli, service and test.

Should be removed in 2028 when Ubuntu 24.04 is the oldest to be supported by exodus

.SH 23. DIM ACCESS
.SH

.SS
var v1 = d1.rows();
.nf
 
.fi
Get the number of rows in the dimensioned array

\fBReturns:\fR A count

.SS
var v1 = d1.cols();
.nf
 
.fi
Get the number of columns in the dimensioned array

\fBReturns:\fR A count

.SS
var v1 = d1.join(delimiter = FM);
.nf
 
.fi
Joins all elements into a single delimited string

\fBReturns:\fR A string var

.SH 24. DIM MUTATION
.SH

.SH 25. DIM CONVERSION
.SH

.SS
d1.sort(reverseorder = false)
.nf
 
.fi
Same as sorter() but returns a new array leaving the original untouched.

.SS
d1.reverse()
.nf
 
.fi
Same as reverser() but returns a new array leaving the original untouched.

.SS
d1.shuffle()
.nf
 
.fi
Same as shuffler() but returns a new array leaving the original untouched.

.SH 26. DIM READ/WRITE
.SH

.SS
if (d1.read(dbfile, key)) ...
.nf
 
.fi
Read a db file record into an array.

Each field in the database record becomes a single element in the array.

\fBReturns:\fR True if the record exists or false if not,

If the array is predimensioned then any excess array elements are initialised to "" and any excess record fields are left unsplit in the final array element. See dim splitter for more info.

If the array is not predimensioned (rows and cols = 0) then it will be dimensioned to have exactly the same number of rows as there are fields in the record being read.

.SS
d1.write(dbfile, key)
.nf
 
.fi
Writes a db file record created from an array.

Each element in the array becomes a separate field in the db record. Any redundant trailing FMs are suppressed.

.SS
if (d1.osread(osfilename, codepage = "")) ...
.nf
 
.fi
Read an entire os text file into an array.

Each line in the os file, delimited by \\n or \\r\\n, becomes a separate element in the array.

\fBcodepage:\fR Optional. Data will be converted from the specified codepage/encoding to UTF8 after being read. If the conversion cannot be performed then return false.

\fBReturns:\fR True if successful or false if not.

If the first \\n in the file is \\r\\n then the whole file will be split using \\r\\n as delimiter.

.SS
if (d1.oswrite(osfilename, codepage = "")) ...
.nf
 
.fi
Creates an entire os text file from an array

Each element of the array becomes one line in the os file delimited by \\n (or \\r\\n if the array was originally osread with \\r\\n delimiter)

Any existing os file is overwritten and replaced.

\fBcodepage:\fR Optional: Data is converted from UTF8 to the required codepage/encoding before output. If the conversion cannot be performed then return false.

\fBReturns:\fR True if successful or false if not.


