//generated by exodus "compile /root/exodus/service/src/sys/htmllib2.cpp"
//#ifndefEXODUS_CALLABLE_HTMLLIB2_H
#define EXODUS_CALLABLE_HTMLLIB2_H

// A 'callable' class and object that allows function call syntax to actually open shared libraries/create Exodus Program objects on the fly.

class Callable_htmllib2 : public CallableBase
{
public:

// A constructor providing:
// 1. the name of the shared library to open,
// 2. the name of the function within the shared library that will create an exodus program object,
Callable_htmllib2(ExoEnv& mv) : CallableBase("htmllib2", "exodusprogrambasecreatedelete_", mv) {}

// Allow assignment of library name to override the default constructed
using CallableBase::operator=;

// A callable member function with the right arguments, returning a var or void
var operator() (in mode, io dataio, in params0="", in params20="", in glang="")
{

 // The first call will link to the shared lib and create/cache an object from it.
 // passing current standard variables in mv
 if (this->pmemberfunction_==NULL)
  this->init();

 // Define a function type (pExodusProgramBaseMemberFunction)
 // that can call the shared library object member function
 // with the right arguments and returning a var or void
 using pExodusProgramBaseMemberFunction = auto (ExodusProgramBase::*)(in,io,in,in,in) -> var;

 // Call the shared library object main function with the right args,
 //  returning a var or void
 return CALLMEMBERFUNCTION(*(this->pobject_),
 ((pExodusProgramBaseMemberFunction) (this->pmemberfunction_)))
  (mode,dataio,params0,params20,glang);

}

// Allow call with only 0 args
var operator() () {
 var mode_in;
 var dataio_io;
 var params0_in = "";
 var params20_in = "";
 var glang_in = "";
 return operator()(mode_in, dataio_io, params0_in, params20_in, glang_in);
}

// Allow call with only 1 arg
var operator() (in mode) {
 var dataio_io;
 var params0_in = "";
 var params20_in = "";
 var glang_in = "";
 return operator()(mode, dataio_io, params0_in, params20_in, glang_in);
}

};

// A callable object of the above type that allows function call syntax to access
// an Exodus program/function initialized with the current mv environment.
Callable_htmllib2 htmllib2{mv};
//#endif
