#ifndef ExodusFunctorS2_H
#define ExodusFunctorS2_H

// generated by genfunctors.cpp

#include <exodus/mvfunctor.h>

template <class T1, class T2> class ExodusFunctorS2 : private ExodusFunctorBase
{
      public:
	ExodusFunctorS2(const std::string libname, const std::string funcname)
	    : ExodusFunctorBase(libname, funcname)
	{
	}

	void operator()()
	{
		checkload();
		typedef void (*ExodusDynamic)(T1 arg1, T2 arg2);
		((ExodusDynamic)pfunction_)(T1(), T2());
		return;
	}

	void operator()(T1 arg1)
	{
		checkload();
		typedef void (*ExodusDynamic)(T1 arg1, T2 arg2);
		((ExodusDynamic)pfunction_)(arg1, T2());
		return;
	}

	void operator()(T1 arg1, T2 arg2)
	{
		checkload();
		typedef void (*ExodusDynamic)(T1 arg1, T2 arg2);
		((ExodusDynamic)pfunction_)(arg1, arg2);
		return;
	}
};
#endif
