//generated by exodus "compile /root/exodus/cli/src/nlist.cpp"
//#ifndefEXODUS_CALLABLE_NLIST_H
#define EXODUS_CALLABLE_NLIST_H

// A 'callable' class and object that allows function call syntax to actually open shared libraries/create Exodus Program objects on the fly.

class Callable_nlist : public Callable
{
public:

// A constructor providing:
// 1. the name of the shared library to open,
// 2. the name of the function within the shared library that will create an exodus program object,
// 3. and the current program's mv environment to share with it.
Callable_nlist(ExoEnv& mv) : Callable("nlist", "exoprogram_createdelete_", mv) {}

// Allow assignment of library name to override the default constructed
using Callable::operator=;

// A callable member function with the right arguments, returning a var or void
var operator() ()
{

 // The first call will link to the shared lib and create/cache an object from it.
 // passing current standard variables in mv
 if (this->pmemberfunc_ == nullptr)
  this->init();

 // Define a function type (pExoProgram_MemberFunc)
 // that can call the shared library object member function
 // with the right arguments and returning a var or void
 using pExoProgram_MemberFunc = auto (ExoProgram::*)() -> var;

 // Call the shared library object main function with the right args,
 //  returning a var or void
 return CALLMEMBERFUNCTION(*(this->plibobject_),
 ((pExoProgram_MemberFunc) (this->pmemberfunc_)))
  ();

}
};

// A callable object of the above type that allows function call syntax to access
// an Exodus program/function initialized with the current mv environment.
Callable_nlist nlist{mv};
//#endif
